/*
 * API Documentation
 *
 * Source of truth and network automation platform
 *
 * The version of the OpenAPI document: 2.4.20 (2.4)
 *
 * Generated by: https://openapi-generator.tech
 */

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AccessTypeEnum {
    #[serde(rename = "Generic")]
    Generic,
    #[serde(rename = "Console")]
    Console,
    #[serde(rename = "gNMI")]
    GNmi,
    #[serde(rename = "HTTP(S)")]
    HttpLeftParenthesisSRightParenthesis,
    #[serde(rename = "NETCONF")]
    Netconf,
    #[serde(rename = "REST")]
    Rest,
    #[serde(rename = "RESTCONF")]
    Restconf,
    #[serde(rename = "SNMP")]
    Snmp,
    #[serde(rename = "SSH")]
    Ssh,
}

impl ToString for AccessTypeEnum {
    fn to_string(&self) -> String {
        match self {
            Self::Generic => String::from("Generic"),
            Self::Console => String::from("Console"),
            Self::GNmi => String::from("gNMI"),
            Self::HttpLeftParenthesisSRightParenthesis => String::from("HTTP(S)"),
            Self::Netconf => String::from("NETCONF"),
            Self::Rest => String::from("REST"),
            Self::Restconf => String::from("RESTCONF"),
            Self::Snmp => String::from("SNMP"),
            Self::Ssh => String::from("SSH"),
        }
    }
}

impl Default for AccessTypeEnum {
    fn default() -> AccessTypeEnum {
        Self::Generic
    }
}
