/*
 * API Documentation
 *
 * Source of truth and network automation platform
 *
 * The version of the OpenAPI document: 3.1.3 (3.1)
 *
 * Generated by: https://openapi-generator.tech
 */

/// ApprovalWorkflowStageResponse : ApprovalWorkflowStageResponse Serializer.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ApprovalWorkflowStageResponse {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<uuid::Uuid>,
    #[serde(rename = "object_type", skip_serializing_if = "Option::is_none")]
    pub object_type: Option<String>,
    /// Human friendly display value
    #[serde(rename = "display", skip_serializing_if = "Option::is_none")]
    pub display: Option<String>,
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    #[serde(rename = "natural_slug", skip_serializing_if = "Option::is_none")]
    pub natural_slug: Option<String>,
    /// User comments to explain the decision that he/she made
    #[serde(rename = "comments", skip_serializing_if = "Option::is_none")]
    pub comments: Option<String>,
    #[serde(rename = "state", skip_serializing_if = "Option::is_none")]
    pub state: Option<crate::models::ApprovalWorkflowStateChoices>,
    #[serde(rename = "approval_workflow_stage")]
    pub approval_workflow_stage:
        Box<crate::models::ApprovalWorkflowStageResponseApprovalWorkflowStage>,
    #[serde(rename = "user")]
    pub user: Box<crate::models::ApprovalWorkflowStageResponseApprovalWorkflowStage>,
    #[serde(
        rename = "last_updated",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub last_updated: Option<Option<String>>,
}

impl ApprovalWorkflowStageResponse {
    /// ApprovalWorkflowStageResponse Serializer.
    pub fn new(
        approval_workflow_stage: crate::models::ApprovalWorkflowStageResponseApprovalWorkflowStage,
        user: crate::models::ApprovalWorkflowStageResponseApprovalWorkflowStage,
    ) -> ApprovalWorkflowStageResponse {
        ApprovalWorkflowStageResponse {
            id: None,
            object_type: None,
            display: None,
            url: None,
            natural_slug: None,
            comments: None,
            state: None,
            approval_workflow_stage: Box::new(approval_workflow_stage),
            user: Box::new(user),
            last_updated: None,
        }
    }
}
