/*
 * API Documentation
 *
 * Source of truth and network automation platform
 *
 * The version of the OpenAPI document: 3.2.2 (3.2)
 *
 * Generated by: https://openapi-generator.tech
 */

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ApprovalWorkflowStateChoices {
    #[serde(rename = "Pending")]
    Pending,
    #[serde(rename = "Approved")]
    Approved,
    #[serde(rename = "Denied")]
    Denied,
    #[serde(rename = "Canceled")]
    Canceled,
    #[serde(rename = "Comment")]
    Comment,
}

impl ToString for ApprovalWorkflowStateChoices {
    fn to_string(&self) -> String {
        match self {
            Self::Pending => String::from("Pending"),
            Self::Approved => String::from("Approved"),
            Self::Denied => String::from("Denied"),
            Self::Canceled => String::from("Canceled"),
            Self::Comment => String::from("Comment"),
        }
    }
}

impl Default for ApprovalWorkflowStateChoices {
    fn default() -> ApprovalWorkflowStateChoices {
        Self::Pending
    }
}
