/*
 * API Documentation
 *
 * Source of truth and network automation platform
 *
 * The version of the OpenAPI document: 3.1.3 (3.1)
 *
 * Generated by: https://openapi-generator.tech
 */

/// ApprovalWorkflowDefinition : ApprovalWorkflowDefinition Serializer.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ApprovalWorkflowDefinition {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<uuid::Uuid>,
    #[serde(rename = "object_type", skip_serializing_if = "Option::is_none")]
    pub object_type: Option<String>,
    /// Human friendly display value
    #[serde(rename = "display", skip_serializing_if = "Option::is_none")]
    pub display: Option<String>,
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    #[serde(rename = "natural_slug", skip_serializing_if = "Option::is_none")]
    pub natural_slug: Option<String>,
    #[serde(rename = "model_content_type")]
    pub model_content_type: String,
    #[serde(rename = "name")]
    pub name: String,
    /// Constraints to filter the objects that can be approved using this workflow.
    #[serde(
        rename = "model_constraints",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub model_constraints: Option<Option<serde_json::Value>>,
    /// Determines workflow relevance when multiple apply. Higher weight wins.
    #[serde(rename = "weight", skip_serializing_if = "Option::is_none")]
    pub weight: Option<i32>,
    #[serde(
        rename = "created",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub created: Option<Option<String>>,
    #[serde(
        rename = "last_updated",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub last_updated: Option<Option<String>>,
    #[serde(rename = "notes_url", skip_serializing_if = "Option::is_none")]
    pub notes_url: Option<String>,
    #[serde(rename = "custom_fields", skip_serializing_if = "Option::is_none")]
    pub custom_fields: Option<::std::collections::HashMap<String, serde_json::Value>>,
}

impl ApprovalWorkflowDefinition {
    /// ApprovalWorkflowDefinition Serializer.
    pub fn new(model_content_type: String, name: String) -> ApprovalWorkflowDefinition {
        ApprovalWorkflowDefinition {
            id: None,
            object_type: None,
            display: None,
            url: None,
            natural_slug: None,
            model_content_type,
            name,
            model_constraints: None,
            weight: None,
            created: None,
            last_updated: None,
            notes_url: None,
            custom_fields: None,
        }
    }
}
