/*
 * API Documentation
 *
 * Source of truth and network automation platform
 *
 * The version of the OpenAPI document: 3.1.2 (3.1)
 *
 * Generated by: https://openapi-generator.tech
 */

/// ApprovalWorkflowDefinitionRequest : ApprovalWorkflowDefinition Serializer.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ApprovalWorkflowDefinitionRequest {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<uuid::Uuid>,
    #[serde(rename = "model_content_type")]
    pub model_content_type: String,
    #[serde(rename = "name")]
    pub name: String,
    /// Constraints to filter the objects that can be approved using this workflow.
    #[serde(
        rename = "model_constraints",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub model_constraints: Option<Option<serde_json::Value>>,
    /// Determines workflow relevance when multiple apply. Higher weight wins.
    #[serde(rename = "weight", skip_serializing_if = "Option::is_none")]
    pub weight: Option<i32>,
    #[serde(rename = "custom_fields", skip_serializing_if = "Option::is_none")]
    pub custom_fields: Option<::std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "relationships", skip_serializing_if = "Option::is_none")]
    pub relationships: Option<
        ::std::collections::HashMap<
            String,
            crate::models::ApprovalWorkflowDefinitionRequestRelationshipsValue,
        >,
    >,
}

impl ApprovalWorkflowDefinitionRequest {
    /// ApprovalWorkflowDefinition Serializer.
    pub fn new(model_content_type: String, name: String) -> ApprovalWorkflowDefinitionRequest {
        ApprovalWorkflowDefinitionRequest {
            id: None,
            model_content_type,
            name,
            model_constraints: None,
            weight: None,
            custom_fields: None,
            relationships: None,
        }
    }
}
