/*
 * API Documentation
 *
 * Source of truth and network automation platform
 *
 * The version of the OpenAPI document: 3.2.2 (3.2)
 *
 * Generated by: https://openapi-generator.tech
 */

/// ApprovalWorkflowStageResponse : Nested read representer for ApprovalWorkflowStageResponse; not exposed as its own endpoint.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ApprovalWorkflowStageResponse {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<uuid::Uuid>,
    #[serde(rename = "object_type", skip_serializing_if = "Option::is_none")]
    pub object_type: Option<String>,
    /// Human friendly display value
    #[serde(rename = "display", skip_serializing_if = "Option::is_none")]
    pub display: Option<String>,
    #[serde(rename = "user", skip_serializing_if = "Option::is_none")]
    pub user: Option<Box<crate::models::User>>,
    /// User comments to explain the decision that he/she made
    #[serde(rename = "comments", skip_serializing_if = "Option::is_none")]
    pub comments: Option<String>,
    #[serde(rename = "state", skip_serializing_if = "Option::is_none")]
    pub state: Option<crate::models::ApprovalWorkflowStateChoices>,
    #[serde(
        rename = "last_updated",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub last_updated: Option<Option<String>>,
}

impl ApprovalWorkflowStageResponse {
    /// Nested read representer for ApprovalWorkflowStageResponse; not exposed as its own endpoint.
    pub fn new() -> ApprovalWorkflowStageResponse {
        ApprovalWorkflowStageResponse {
            id: None,
            object_type: None,
            display: None,
            user: None,
            comments: None,
            state: None,
            last_updated: None,
        }
    }
}
