/*
 * API Documentation
 *
 * Source of truth and network automation platform
 *
 * The version of the OpenAPI document: 3.1.2 (3.1)
 *
 * Generated by: https://openapi-generator.tech
 */

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AuthenticationMethodEnum {
    #[serde(rename = "PSK")]
    Psk,
    #[serde(rename = "RSA")]
    Rsa,
    #[serde(rename = "ECDSA")]
    Ecdsa,
    #[serde(rename = "Certificate")]
    Certificate,
}

impl ToString for AuthenticationMethodEnum {
    fn to_string(&self) -> String {
        match self {
            Self::Psk => String::from("PSK"),
            Self::Rsa => String::from("RSA"),
            Self::Ecdsa => String::from("ECDSA"),
            Self::Certificate => String::from("Certificate"),
        }
    }
}

impl Default for AuthenticationMethodEnum {
    fn default() -> AuthenticationMethodEnum {
        Self::Psk
    }
}
