/*
 * API Documentation
 *
 * Source of truth and network automation platform
 *
 * The version of the OpenAPI document: 2.4.20 (2.4)
 *
 * Generated by: https://openapi-generator.tech
 */

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AuthenticationEnum {
    #[serde(rename = "Open")]
    Open,
    #[serde(rename = "WPA2 Personal")]
    Wpa2Personal,
    #[serde(rename = "WPA2 Enterprise")]
    Wpa2Enterprise,
    #[serde(rename = "Enhanced Open")]
    EnhancedOpen,
    #[serde(rename = "WPA3 Personal")]
    Wpa3Personal,
    #[serde(rename = "WPA3 SAE")]
    Wpa3Sae,
    #[serde(rename = "WPA3 Enterprise")]
    Wpa3Enterprise,
    #[serde(rename = "WPA3 Enterprise 192Bit")]
    Wpa3Enterprise192Bit,
}

impl ToString for AuthenticationEnum {
    fn to_string(&self) -> String {
        match self {
            Self::Open => String::from("Open"),
            Self::Wpa2Personal => String::from("WPA2 Personal"),
            Self::Wpa2Enterprise => String::from("WPA2 Enterprise"),
            Self::EnhancedOpen => String::from("Enhanced Open"),
            Self::Wpa3Personal => String::from("WPA3 Personal"),
            Self::Wpa3Sae => String::from("WPA3 SAE"),
            Self::Wpa3Enterprise => String::from("WPA3 Enterprise"),
            Self::Wpa3Enterprise192Bit => String::from("WPA3 Enterprise 192Bit"),
        }
    }
}

impl Default for AuthenticationEnum {
    fn default() -> AuthenticationEnum {
        Self::Open
    }
}
