/*
 * API Documentation
 *
 * Source of truth and network automation platform
 *
 * The version of the OpenAPI document: 2.4.20 (2.4)
 *
 * Generated by: https://openapi-generator.tech
 */

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum BlankEnum {
    #[serde(rename = "")]
    Empty,
}

impl ToString for BlankEnum {
    fn to_string(&self) -> String {
        match self {
            Self::Empty => String::from(""),
        }
    }
}

impl Default for BlankEnum {
    fn default() -> BlankEnum {
        Self::Empty
    }
}
