/*
 * API Documentation
 *
 * Source of truth and network automation platform
 *
 * The version of the OpenAPI document: 2.4.20 (2.4)
 *
 * Generated by: https://openapi-generator.tech
 */

/// BulkWritableMetadataChoiceRequest : Extends the built-in ModelSerializer to enforce calling full_clean() on a copy of the associated instance during validation. (DRF does not do this by default; see <https://github.com/encode/django-rest-framework/issues/3144>)

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct BulkWritableMetadataChoiceRequest {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "value")]
    pub value: String,
    /// Higher weights appear later in the list
    #[serde(rename = "weight", skip_serializing_if = "Option::is_none")]
    pub weight: Option<i32>,
    #[serde(rename = "metadata_type")]
    pub metadata_type: Box<crate::models::BulkWritableCableRequestStatus>,
}

impl BulkWritableMetadataChoiceRequest {
    /// Extends the built-in ModelSerializer to enforce calling full_clean() on a copy of the associated instance during validation. (DRF does not do this by default; see <https://github.com/encode/django-rest-framework/issues/3144>)
    pub fn new(
        id: uuid::Uuid,
        value: String,
        metadata_type: crate::models::BulkWritableCableRequestStatus,
    ) -> BulkWritableMetadataChoiceRequest {
        BulkWritableMetadataChoiceRequest {
            id,
            value,
            weight: None,
            metadata_type: Box::new(metadata_type),
        }
    }
}
