/*
 * API Documentation
 *
 * Source of truth and network automation platform
 *
 * The version of the OpenAPI document: 3.2.2 (3.2)
 *
 * Generated by: https://openapi-generator.tech
 */

/// BulkWritableCableRequestCableType : The cable type defining this cable's lane structure and other properties.May be null for standard point-to-point cables.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct BulkWritableCableRequestCableType {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<Box<crate::models::ApprovalWorkflowApprovalWorkflowDefinitionId>>,
    #[serde(rename = "object_type", skip_serializing_if = "Option::is_none")]
    pub object_type: Option<String>,
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
}

impl BulkWritableCableRequestCableType {
    /// The cable type defining this cable's lane structure and other properties.May be null for standard point-to-point cables.
    pub fn new() -> BulkWritableCableRequestCableType {
        BulkWritableCableRequestCableType {
            id: None,
            object_type: None,
            url: None,
        }
    }
}
