/*
 * API Documentation
 *
 * Source of truth and network automation platform
 *
 * The version of the OpenAPI document: 3.1.4 (3.1)
 *
 * Generated by: https://openapi-generator.tech
 */

/// BulkWritableControllerManagedDeviceGroupWirelessNetworkAssignmentRequest : Extends the built-in ModelSerializer to enforce calling full_clean() on a copy of the associated instance during validation. (DRF does not do this by default; see <https://github.com/encode/django-rest-framework/issues/3144>)

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct BulkWritableControllerManagedDeviceGroupWirelessNetworkAssignmentRequest {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "controller_managed_device_group")]
    pub controller_managed_device_group:
        Box<crate::models::ApprovalWorkflowStageResponseApprovalWorkflowStage>,
    #[serde(rename = "wireless_network")]
    pub wireless_network: Box<crate::models::ApprovalWorkflowStageResponseApprovalWorkflowStage>,
    #[serde(
        rename = "vlan",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub vlan: Option<Option<Box<crate::models::ApprovalWorkflowUser>>>,
}

impl BulkWritableControllerManagedDeviceGroupWirelessNetworkAssignmentRequest {
    /// Extends the built-in ModelSerializer to enforce calling full_clean() on a copy of the associated instance during validation. (DRF does not do this by default; see <https://github.com/encode/django-rest-framework/issues/3144>)
    pub fn new(
        id: uuid::Uuid,
        controller_managed_device_group: crate::models::ApprovalWorkflowStageResponseApprovalWorkflowStage,
        wireless_network: crate::models::ApprovalWorkflowStageResponseApprovalWorkflowStage,
    ) -> BulkWritableControllerManagedDeviceGroupWirelessNetworkAssignmentRequest {
        BulkWritableControllerManagedDeviceGroupWirelessNetworkAssignmentRequest {
            id,
            controller_managed_device_group: Box::new(controller_managed_device_group),
            wireless_network: Box::new(wireless_network),
            vlan: None,
        }
    }
}
