/*
 * API Documentation
 *
 * Source of truth and network automation platform
 *
 * The version of the OpenAPI document: 3.1.0 (3.1)
 *
 * Generated by: https://openapi-generator.tech
 */

/// BulkWritableCloudNetworkPrefixAssignmentRequest : Extends the built-in ModelSerializer to enforce calling full_clean() on a copy of the associated instance during validation. (DRF does not do this by default; see <https://github.com/encode/django-rest-framework/issues/3144>)

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct BulkWritableCloudNetworkPrefixAssignmentRequest {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "cloud_network")]
    pub cloud_network: Box<crate::models::ApprovalWorkflowStageResponseApprovalWorkflowStage>,
    #[serde(rename = "prefix")]
    pub prefix: Box<crate::models::ApprovalWorkflowStageResponseApprovalWorkflowStage>,
}

impl BulkWritableCloudNetworkPrefixAssignmentRequest {
    /// Extends the built-in ModelSerializer to enforce calling full_clean() on a copy of the associated instance during validation. (DRF does not do this by default; see <https://github.com/encode/django-rest-framework/issues/3144>)
    pub fn new(
        id: uuid::Uuid,
        cloud_network: crate::models::ApprovalWorkflowStageResponseApprovalWorkflowStage,
        prefix: crate::models::ApprovalWorkflowStageResponseApprovalWorkflowStage,
    ) -> BulkWritableCloudNetworkPrefixAssignmentRequest {
        BulkWritableCloudNetworkPrefixAssignmentRequest {
            id,
            cloud_network: Box::new(cloud_network),
            prefix: Box::new(prefix),
        }
    }
}
