/*
 * API Documentation
 *
 * Source of truth and network automation platform
 *
 * The version of the OpenAPI document: 3.2.2 (3.2)
 *
 * Generated by: https://openapi-generator.tech
 */

/// BulkWritableLoadBalancerPoolMemberRequest : LoadBalancerPoolMember Serializer.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct BulkWritableLoadBalancerPoolMemberRequest {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    /// Optional label for the load balancer pool member.
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
    #[serde(rename = "port")]
    pub port: i32,
    #[serde(rename = "ssl_offload", skip_serializing_if = "Option::is_none")]
    pub ssl_offload: Option<bool>,
    #[serde(rename = "ip_address")]
    pub ip_address: Box<crate::models::BulkWritableCableRequestStatus>,
    #[serde(rename = "load_balancer_pool")]
    pub load_balancer_pool: Box<crate::models::BulkWritableCableRequestStatus>,
    #[serde(
        rename = "health_check_monitor",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub health_check_monitor: Option<Option<Box<crate::models::ApprovalWorkflowUser>>>,
    #[serde(
        rename = "tenant",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub tenant: Option<Option<Box<crate::models::ApprovalWorkflowUser>>>,
    #[serde(rename = "status")]
    pub status: Box<crate::models::BulkWritableCableRequestStatus>,
    /// Custom field data for this object, keyed by each applicable Custom Field's `key`. Value types vary with the custom field's type (text, integer, boolean, date, URL, JSON, select, multi-select); undefined values are `null`. On write, the payload is merged with existing values (PATCH-style: keys omitted from the payload are left untouched), and keys that do not correspond to a defined custom field are ignored.
    #[serde(rename = "custom_fields", skip_serializing_if = "Option::is_none")]
    pub custom_fields: Option<::std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "relationships", skip_serializing_if = "Option::is_none")]
    pub relationships: Option<
        ::std::collections::HashMap<
            String,
            crate::models::ApprovalWorkflowDefinitionRequestRelationshipsValue,
        >,
    >,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<crate::models::BulkWritableCableRequestStatus>>,
}

impl BulkWritableLoadBalancerPoolMemberRequest {
    /// LoadBalancerPoolMember Serializer.
    pub fn new(
        id: uuid::Uuid,
        port: i32,
        ip_address: crate::models::BulkWritableCableRequestStatus,
        load_balancer_pool: crate::models::BulkWritableCableRequestStatus,
        status: crate::models::BulkWritableCableRequestStatus,
    ) -> BulkWritableLoadBalancerPoolMemberRequest {
        BulkWritableLoadBalancerPoolMemberRequest {
            id,
            label: None,
            port,
            ssl_offload: None,
            ip_address: Box::new(ip_address),
            load_balancer_pool: Box::new(load_balancer_pool),
            health_check_monitor: None,
            tenant: None,
            status: Box::new(status),
            custom_fields: None,
            relationships: None,
            tags: None,
        }
    }
}
