/*
 * API Documentation
 *
 * Source of truth and network automation platform
 *
 * The version of the OpenAPI document: 2.4.20 (2.4)
 *
 * Generated by: https://openapi-generator.tech
 */

/// BulkWritableControllerManagedDeviceGroupRequest : Base class to use for serializers based on OrganizationalModel or PrimaryModel.  Can also be used for models derived from BaseModel, so long as they support custom fields, notes, and relationships.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct BulkWritableControllerManagedDeviceGroupRequest {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(
        rename = "capabilities",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub capabilities: Option<Option<Vec<crate::models::CapabilitiesEnum>>>,
    /// Name of the controller device group
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Weight of the controller device group, used to sort the groups within its parent group
    #[serde(rename = "weight", skip_serializing_if = "Option::is_none")]
    pub weight: Option<i32>,
    #[serde(
        rename = "parent",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub parent: Option<Option<Box<crate::models::BulkWritableCircuitRequestTenant>>>,
    #[serde(rename = "controller")]
    pub controller: Box<crate::models::BulkWritableControllerManagedDeviceGroupRequestController>,
    #[serde(
        rename = "tenant",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub tenant: Option<Option<Box<crate::models::BulkWritableCircuitRequestTenant>>>,
    #[serde(rename = "custom_fields", skip_serializing_if = "Option::is_none")]
    pub custom_fields: Option<::std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "relationships", skip_serializing_if = "Option::is_none")]
    pub relationships: Option<
        ::std::collections::HashMap<
            String,
            crate::models::BulkWritableCableRequestRelationshipsValue,
        >,
    >,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<crate::models::BulkWritableCableRequestStatus>>,
}

impl BulkWritableControllerManagedDeviceGroupRequest {
    /// Base class to use for serializers based on OrganizationalModel or PrimaryModel.  Can also be used for models derived from BaseModel, so long as they support custom fields, notes, and relationships.
    pub fn new(
        id: uuid::Uuid,
        name: String,
        controller: crate::models::BulkWritableControllerManagedDeviceGroupRequestController,
    ) -> BulkWritableControllerManagedDeviceGroupRequest {
        BulkWritableControllerManagedDeviceGroupRequest {
            id,
            capabilities: None,
            name,
            description: None,
            weight: None,
            parent: None,
            controller: Box::new(controller),
            tenant: None,
            custom_fields: None,
            relationships: None,
            tags: None,
        }
    }
}
