/*
 * API Documentation
 *
 * Source of truth and network automation platform
 *
 * The version of the OpenAPI document: 3.2.2 (3.2)
 *
 * Generated by: https://openapi-generator.tech
 */

/// BulkWritableVpnTunnelRequestEndpointA : Tunnel termination A

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct BulkWritableVpnTunnelRequestEndpointA {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<Box<crate::models::ApprovalWorkflowApprovalWorkflowDefinitionId>>,
    #[serde(rename = "object_type", skip_serializing_if = "Option::is_none")]
    pub object_type: Option<String>,
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
}

impl BulkWritableVpnTunnelRequestEndpointA {
    /// Tunnel termination A
    pub fn new() -> BulkWritableVpnTunnelRequestEndpointA {
        BulkWritableVpnTunnelRequestEndpointA {
            id: None,
            object_type: None,
            url: None,
        }
    }
}
