/*
 * API Documentation
 *
 * Source of truth and network automation platform
 *
 * The version of the OpenAPI document: 3.1.4 (3.1)
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct BulkWritableCertificateProfileRequestCertificateType {}

impl BulkWritableCertificateProfileRequestCertificateType {
    pub fn new() -> BulkWritableCertificateProfileRequestCertificateType {
        BulkWritableCertificateProfileRequestCertificateType {}
    }
}
