/*
 * API Documentation
 *
 * Source of truth and network automation platform
 *
 * The version of the OpenAPI document: 2.4.20 (2.4)
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct BulkWritableCableRequestRelationshipsValueSourceObjectsInner {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<uuid::Uuid>,
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    #[serde(rename = "display", skip_serializing_if = "Option::is_none")]
    pub display: Option<String>,
}

impl BulkWritableCableRequestRelationshipsValueSourceObjectsInner {
    pub fn new() -> BulkWritableCableRequestRelationshipsValueSourceObjectsInner {
        BulkWritableCableRequestRelationshipsValueSourceObjectsInner {
            id: None,
            url: None,
            display: None,
        }
    }
}
