/*
 * API Documentation
 *
 * Source of truth and network automation platform
 *
 * The version of the OpenAPI document: 3.1.0 (3.1)
 *
 * Generated by: https://openapi-generator.tech
 */

/// BulkWritableApprovalWorkflowRequest : ApprovalWorkflow Serializer.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct BulkWritableApprovalWorkflowRequest {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "object_under_review_content_type")]
    pub object_under_review_content_type: String,
    #[serde(rename = "object_under_review_object_id")]
    pub object_under_review_object_id: uuid::Uuid,
    #[serde(rename = "current_state", skip_serializing_if = "Option::is_none")]
    pub current_state: Option<crate::models::ApprovalWorkflowStateChoices>,
    #[serde(
        rename = "approval_workflow_definition",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub approval_workflow_definition:
        Option<Option<Box<crate::models::ApprovalWorkflowApprovalWorkflowDefinition>>>,
    #[serde(
        rename = "user",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub user: Option<Option<Box<crate::models::ApprovalWorkflowUser>>>,
    #[serde(rename = "custom_fields", skip_serializing_if = "Option::is_none")]
    pub custom_fields: Option<::std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "relationships", skip_serializing_if = "Option::is_none")]
    pub relationships: Option<
        ::std::collections::HashMap<
            String,
            crate::models::ApprovalWorkflowDefinitionRequestRelationshipsValue,
        >,
    >,
}

impl BulkWritableApprovalWorkflowRequest {
    /// ApprovalWorkflow Serializer.
    pub fn new(
        id: uuid::Uuid,
        object_under_review_content_type: String,
        object_under_review_object_id: uuid::Uuid,
    ) -> BulkWritableApprovalWorkflowRequest {
        BulkWritableApprovalWorkflowRequest {
            id,
            object_under_review_content_type,
            object_under_review_object_id,
            current_state: None,
            approval_workflow_definition: None,
            user: None,
            custom_fields: None,
            relationships: None,
        }
    }
}
