/*
 * API Documentation
 *
 * Source of truth and network automation platform
 *
 * The version of the OpenAPI document: 3.1.3 (3.1)
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct BulkWritableVirtualServerRequestLoadBalancerType {}

impl BulkWritableVirtualServerRequestLoadBalancerType {
    pub fn new() -> BulkWritableVirtualServerRequestLoadBalancerType {
        BulkWritableVirtualServerRequestLoadBalancerType {}
    }
}
