/*
 * API Documentation
 *
 * Source of truth and network automation platform
 *
 * The version of the OpenAPI document: 2.4.20 (2.4)
 *
 * Generated by: https://openapi-generator.tech
 */

/// BulkWritablePrefixRequestParent : The parent Prefix of this Prefix.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct BulkWritablePrefixRequestParent {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<Box<crate::models::BulkWritableCableRequestStatusId>>,
    #[serde(rename = "object_type", skip_serializing_if = "Option::is_none")]
    pub object_type: Option<String>,
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
}

impl BulkWritablePrefixRequestParent {
    /// The parent Prefix of this Prefix.
    pub fn new() -> BulkWritablePrefixRequestParent {
        BulkWritablePrefixRequestParent {
            id: None,
            object_type: None,
            url: None,
        }
    }
}
