/*
 * API Documentation
 *
 * Source of truth and network automation platform
 *
 * The version of the OpenAPI document: 3.2.2 (3.2)
 *
 * Generated by: https://openapi-generator.tech
 */

/// BulkWritableVirtualServerCertificateProfileAssignmentRequest : VirtualServerCertificateProfileAssignment Serializer.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct BulkWritableVirtualServerCertificateProfileAssignmentRequest {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "virtual_server")]
    pub virtual_server: Box<crate::models::BulkWritableCableRequestStatus>,
    #[serde(rename = "certificate_profile")]
    pub certificate_profile: Box<crate::models::BulkWritableCableRequestStatus>,
}

impl BulkWritableVirtualServerCertificateProfileAssignmentRequest {
    /// VirtualServerCertificateProfileAssignment Serializer.
    pub fn new(
        id: uuid::Uuid,
        virtual_server: crate::models::BulkWritableCableRequestStatus,
        certificate_profile: crate::models::BulkWritableCableRequestStatus,
    ) -> BulkWritableVirtualServerCertificateProfileAssignmentRequest {
        BulkWritableVirtualServerCertificateProfileAssignmentRequest {
            id,
            virtual_server: Box::new(virtual_server),
            certificate_profile: Box::new(certificate_profile),
        }
    }
}
