/*
 * API Documentation
 *
 * Source of truth and network automation platform
 *
 * The version of the OpenAPI document: 3.1.2 (3.1)
 *
 * Generated by: https://openapi-generator.tech
 */

/// BulkWritableDeviceClusterAssignmentRequest : Serializer for DeviceClusterAssignment model.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct BulkWritableDeviceClusterAssignmentRequest {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "device")]
    pub device: Box<crate::models::ApprovalWorkflowStageResponseApprovalWorkflowStage>,
    #[serde(rename = "cluster")]
    pub cluster: Box<crate::models::ApprovalWorkflowStageResponseApprovalWorkflowStage>,
}

impl BulkWritableDeviceClusterAssignmentRequest {
    /// Serializer for DeviceClusterAssignment model.
    pub fn new(
        id: uuid::Uuid,
        device: crate::models::ApprovalWorkflowStageResponseApprovalWorkflowStage,
        cluster: crate::models::ApprovalWorkflowStageResponseApprovalWorkflowStage,
    ) -> BulkWritableDeviceClusterAssignmentRequest {
        BulkWritableDeviceClusterAssignmentRequest {
            id,
            device: Box::new(device),
            cluster: Box::new(cluster),
        }
    }
}
