/*
 * API Documentation
 *
 * Source of truth and network automation platform
 *
 * The version of the OpenAPI document: 2.4.20 (2.4)
 *
 * Generated by: https://openapi-generator.tech
 */

/// BulkWritableInterfaceVdcAssignmentRequest : Extends the built-in ModelSerializer to enforce calling full_clean() on a copy of the associated instance during validation. (DRF does not do this by default; see <https://github.com/encode/django-rest-framework/issues/3144>)

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct BulkWritableInterfaceVdcAssignmentRequest {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "virtual_device_context")]
    pub virtual_device_context: Box<crate::models::BulkWritableCableRequestStatus>,
    #[serde(rename = "interface")]
    pub interface: Box<crate::models::BulkWritableCableRequestStatus>,
}

impl BulkWritableInterfaceVdcAssignmentRequest {
    /// Extends the built-in ModelSerializer to enforce calling full_clean() on a copy of the associated instance during validation. (DRF does not do this by default; see <https://github.com/encode/django-rest-framework/issues/3144>)
    pub fn new(
        id: uuid::Uuid,
        virtual_device_context: crate::models::BulkWritableCableRequestStatus,
        interface: crate::models::BulkWritableCableRequestStatus,
    ) -> BulkWritableInterfaceVdcAssignmentRequest {
        BulkWritableInterfaceVdcAssignmentRequest {
            id,
            virtual_device_context: Box::new(virtual_device_context),
            interface: Box::new(interface),
        }
    }
}
