/*
 * API Documentation
 *
 * Source of truth and network automation platform
 *
 * The version of the OpenAPI document: 2.4.20 (2.4)
 *
 * Generated by: https://openapi-generator.tech
 */

/// BulkWritableObjectMetadataRequest : Extends the built-in ModelSerializer to enforce calling full_clean() on a copy of the associated instance during validation. (DRF does not do this by default; see <https://github.com/encode/django-rest-framework/issues/3144>)

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct BulkWritableObjectMetadataRequest {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "assigned_object_type")]
    pub assigned_object_type: String,
    #[serde(
        rename = "value",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub value: Option<Option<serde_json::Value>>,
    /// List of scoped fields, only direct fields on the model
    #[serde(
        rename = "scoped_fields",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub scoped_fields: Option<Option<serde_json::Value>>,
    #[serde(rename = "assigned_object_id")]
    pub assigned_object_id: uuid::Uuid,
    #[serde(rename = "metadata_type")]
    pub metadata_type: Box<crate::models::BulkWritableCableRequestStatus>,
    #[serde(
        rename = "contact",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub contact: Option<Option<Box<crate::models::BulkWritableCircuitRequestTenant>>>,
    #[serde(
        rename = "team",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub team: Option<Option<Box<crate::models::BulkWritableCircuitRequestTenant>>>,
}

impl BulkWritableObjectMetadataRequest {
    /// Extends the built-in ModelSerializer to enforce calling full_clean() on a copy of the associated instance during validation. (DRF does not do this by default; see <https://github.com/encode/django-rest-framework/issues/3144>)
    pub fn new(
        id: uuid::Uuid,
        assigned_object_type: String,
        assigned_object_id: uuid::Uuid,
        metadata_type: crate::models::BulkWritableCableRequestStatus,
    ) -> BulkWritableObjectMetadataRequest {
        BulkWritableObjectMetadataRequest {
            id,
            assigned_object_type,
            value: None,
            scoped_fields: None,
            assigned_object_id,
            metadata_type: Box::new(metadata_type),
            contact: None,
            team: None,
        }
    }
}
