/*
 * API Documentation
 *
 * Source of truth and network automation platform
 *
 * The version of the OpenAPI document: 3.2.2 (3.2)
 *
 * Generated by: https://openapi-generator.tech
 */

/// BulkWritableObjectPermissionRequest : Extends the built-in ModelSerializer to enforce calling full_clean() on a copy of the associated instance during validation. (DRF does not do this by default; see <https://github.com/encode/django-rest-framework/issues/3144>)

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct BulkWritableObjectPermissionRequest {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "object_types")]
    pub object_types: Vec<String>,
    /// The list of actions granted by this permission
    #[serde(rename = "actions")]
    pub actions: Vec<String>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
    /// Queryset filter matching the applicable objects of the selected type(s)
    #[serde(
        rename = "constraints",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub constraints: Option<Option<serde_json::Value>>,
    #[serde(rename = "groups", skip_serializing_if = "Option::is_none")]
    pub groups: Option<Vec<crate::models::BulkWritableCableRequestStatus>>,
    #[serde(rename = "users", skip_serializing_if = "Option::is_none")]
    pub users: Option<Vec<crate::models::BulkWritableCableRequestStatus>>,
}

impl BulkWritableObjectPermissionRequest {
    /// Extends the built-in ModelSerializer to enforce calling full_clean() on a copy of the associated instance during validation. (DRF does not do this by default; see <https://github.com/encode/django-rest-framework/issues/3144>)
    pub fn new(
        id: uuid::Uuid,
        object_types: Vec<String>,
        actions: Vec<String>,
        name: String,
    ) -> BulkWritableObjectPermissionRequest {
        BulkWritableObjectPermissionRequest {
            id,
            object_types,
            actions,
            name,
            description: None,
            enabled: None,
            constraints: None,
            groups: None,
            users: None,
        }
    }
}
