/*
 * API Documentation
 *
 * Source of truth and network automation platform
 *
 * The version of the OpenAPI document: 3.2.2 (3.2)
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct BulkWritableCableTypeRequestMappingInner {
    #[serde(rename = "label")]
    pub label: String,
    #[serde(rename = "a_connector")]
    pub a_connector: i32,
    #[serde(rename = "a_position")]
    pub a_position: i32,
    #[serde(rename = "b_connector")]
    pub b_connector: i32,
    #[serde(rename = "b_position")]
    pub b_position: i32,
}

impl BulkWritableCableTypeRequestMappingInner {
    pub fn new(
        label: String,
        a_connector: i32,
        a_position: i32,
        b_connector: i32,
        b_position: i32,
    ) -> BulkWritableCableTypeRequestMappingInner {
        BulkWritableCableTypeRequestMappingInner {
            label,
            a_connector,
            a_position,
            b_connector,
            b_position,
        }
    }
}
