/*
 * API Documentation
 *
 * Source of truth and network automation platform
 *
 * The version of the OpenAPI document: 3.1.0 (3.1)
 *
 * Generated by: https://openapi-generator.tech
 */

/// BulkWritableDataComplianceRequest : Serializer for DataCompliance.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct BulkWritableDataComplianceRequest {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "compliance_class_name")]
    pub compliance_class_name: String,
    #[serde(rename = "object_id")]
    pub object_id: uuid::Uuid,
    #[serde(
        rename = "validated_object_str",
        skip_serializing_if = "Option::is_none"
    )]
    pub validated_object_str: Option<String>,
    #[serde(
        rename = "validated_attribute",
        skip_serializing_if = "Option::is_none"
    )]
    pub validated_attribute: Option<String>,
    #[serde(
        rename = "validated_attribute_value",
        skip_serializing_if = "Option::is_none"
    )]
    pub validated_attribute_value: Option<String>,
    #[serde(rename = "valid")]
    pub valid: bool,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    #[serde(rename = "content_type")]
    pub content_type: Box<crate::models::ApprovalWorkflowStageResponseApprovalWorkflowStage>,
    #[serde(rename = "custom_fields", skip_serializing_if = "Option::is_none")]
    pub custom_fields: Option<::std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "relationships", skip_serializing_if = "Option::is_none")]
    pub relationships: Option<
        ::std::collections::HashMap<
            String,
            crate::models::ApprovalWorkflowDefinitionRequestRelationshipsValue,
        >,
    >,
}

impl BulkWritableDataComplianceRequest {
    /// Serializer for DataCompliance.
    pub fn new(
        id: uuid::Uuid,
        compliance_class_name: String,
        object_id: uuid::Uuid,
        valid: bool,
        content_type: crate::models::ApprovalWorkflowStageResponseApprovalWorkflowStage,
    ) -> BulkWritableDataComplianceRequest {
        BulkWritableDataComplianceRequest {
            id,
            compliance_class_name,
            object_id,
            validated_object_str: None,
            validated_attribute: None,
            validated_attribute_value: None,
            valid,
            message: None,
            content_type: Box::new(content_type),
            custom_fields: None,
            relationships: None,
        }
    }
}
