/*
 * API Documentation
 *
 * Source of truth and network automation platform
 *
 * The version of the OpenAPI document: 2.4.20 (2.4)
 *
 * Generated by: https://openapi-generator.tech
 */

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ButtonClassEnum {
    #[serde(rename = "default")]
    Default,
    #[serde(rename = "primary")]
    Primary,
    #[serde(rename = "success")]
    Success,
    #[serde(rename = "info")]
    Info,
    #[serde(rename = "warning")]
    Warning,
    #[serde(rename = "danger")]
    Danger,
    #[serde(rename = "link")]
    Link,
}

impl ToString for ButtonClassEnum {
    fn to_string(&self) -> String {
        match self {
            Self::Default => String::from("default"),
            Self::Primary => String::from("primary"),
            Self::Success => String::from("success"),
            Self::Info => String::from("info"),
            Self::Warning => String::from("warning"),
            Self::Danger => String::from("danger"),
            Self::Link => String::from("link"),
        }
    }
}

impl Default for ButtonClassEnum {
    fn default() -> ButtonClassEnum {
        Self::Default
    }
}
