/*
 * API Documentation
 *
 * Source of truth and network automation platform
 *
 * The version of the OpenAPI document: 2.4.20 (2.4)
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "object_type")]
pub enum CableTermination {
    #[serde(rename = "circuits.circuittermination")]
    NestedCircuitTermination {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<uuid::Uuid>,
        #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
        url: Option<String>,
    },
    #[serde(rename = "dcim.consoleport")]
    NestedConsolePort {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<uuid::Uuid>,
        #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
        url: Option<String>,
    },
    #[serde(rename = "dcim.consoleserverport")]
    NestedConsoleServerPort {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<uuid::Uuid>,
        #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
        url: Option<String>,
    },
    #[serde(rename = "dcim.frontport")]
    NestedFrontPort {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<uuid::Uuid>,
        #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
        url: Option<String>,
    },
    #[serde(rename = "dcim.interface")]
    NestedInterface {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<uuid::Uuid>,
        #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
        url: Option<String>,
    },
    #[serde(rename = "dcim.powerfeed")]
    NestedPowerFeed {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<uuid::Uuid>,
        #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
        url: Option<String>,
    },
    #[serde(rename = "dcim.poweroutlet")]
    NestedPowerOutlet {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<uuid::Uuid>,
        #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
        url: Option<String>,
    },
    #[serde(rename = "dcim.powerport")]
    NestedPowerPort {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<uuid::Uuid>,
        #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
        url: Option<String>,
    },
    #[serde(rename = "dcim.rearport")]
    NestedRearPort {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<uuid::Uuid>,
        #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
        url: Option<String>,
    },
}
