/*
 * API Documentation
 *
 * Source of truth and network automation platform
 *
 * The version of the OpenAPI document: 2.4.20 (2.4)
 *
 * Generated by: https://openapi-generator.tech
 */

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CapabilitiesEnum {
    #[serde(rename = "wireless")]
    Wireless,
}

impl ToString for CapabilitiesEnum {
    fn to_string(&self) -> String {
        match self {
            Self::Wireless => String::from("wireless"),
        }
    }
}

impl Default for CapabilitiesEnum {
    fn default() -> CapabilitiesEnum {
        Self::Wireless
    }
}
