/*
 * API Documentation
 *
 * Source of truth and network automation platform
 *
 * The version of the OpenAPI document: 3.2.2 (3.2)
 *
 * Generated by: https://openapi-generator.tech
 */

/// CertificateProfileRequest : CertificateProfile Serializer.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CertificateProfileRequest {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<uuid::Uuid>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "certificate_type", skip_serializing_if = "Option::is_none")]
    pub certificate_type:
        Option<Box<crate::models::BulkWritableCertificateProfileRequestCertificateType>>,
    #[serde(
        rename = "certificate_file_path",
        skip_serializing_if = "Option::is_none"
    )]
    pub certificate_file_path: Option<String>,
    #[serde(rename = "chain_file_path", skip_serializing_if = "Option::is_none")]
    pub chain_file_path: Option<String>,
    #[serde(rename = "key_file_path", skip_serializing_if = "Option::is_none")]
    pub key_file_path: Option<String>,
    #[serde(
        rename = "expiration_date",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub expiration_date: Option<Option<String>>,
    #[serde(rename = "cipher", skip_serializing_if = "Option::is_none")]
    pub cipher: Option<String>,
    #[serde(
        rename = "tenant",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub tenant: Option<Option<Box<crate::models::ApprovalWorkflowUser>>>,
    /// Custom field data for this object, keyed by each applicable Custom Field's `key`. Value types vary with the custom field's type (text, integer, boolean, date, URL, JSON, select, multi-select); undefined values are `null`. On write, the payload is merged with existing values (PATCH-style: keys omitted from the payload are left untouched), and keys that do not correspond to a defined custom field are ignored.
    #[serde(rename = "custom_fields", skip_serializing_if = "Option::is_none")]
    pub custom_fields: Option<::std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "relationships", skip_serializing_if = "Option::is_none")]
    pub relationships: Option<
        ::std::collections::HashMap<
            String,
            crate::models::ApprovalWorkflowDefinitionRequestRelationshipsValue,
        >,
    >,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<crate::models::BulkWritableCableRequestStatus>>,
}

impl CertificateProfileRequest {
    /// CertificateProfile Serializer.
    pub fn new(name: String) -> CertificateProfileRequest {
        CertificateProfileRequest {
            id: None,
            name,
            certificate_type: None,
            certificate_file_path: None,
            chain_file_path: None,
            key_file_path: None,
            expiration_date: None,
            cipher: None,
            tenant: None,
            custom_fields: None,
            relationships: None,
            tags: None,
        }
    }
}
