/*
 * API Documentation
 *
 * Source of truth and network automation platform
 *
 * The version of the OpenAPI document: 3.2.2 (3.2)
 *
 * Generated by: https://openapi-generator.tech
 */

/// CloudResourceTypeRequest : Base class to use for serializers based on OrganizationalModel or PrimaryModel.  Can also be used for models derived from BaseModel, so long as they support custom fields, notes, and relationships.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CloudResourceTypeRequest {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<uuid::Uuid>,
    #[serde(rename = "content_types")]
    pub content_types: Vec<String>,
    /// Type of cloud objects
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(
        rename = "config_schema",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub config_schema: Option<Option<serde_json::Value>>,
    #[serde(rename = "provider")]
    pub provider: Box<crate::models::BulkWritableCloudAccountRequestProvider>,
    /// Custom field data for this object, keyed by each applicable Custom Field's `key`. Value types vary with the custom field's type (text, integer, boolean, date, URL, JSON, select, multi-select); undefined values are `null`. On write, the payload is merged with existing values (PATCH-style: keys omitted from the payload are left untouched), and keys that do not correspond to a defined custom field are ignored.
    #[serde(rename = "custom_fields", skip_serializing_if = "Option::is_none")]
    pub custom_fields: Option<::std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "relationships", skip_serializing_if = "Option::is_none")]
    pub relationships: Option<
        ::std::collections::HashMap<
            String,
            crate::models::ApprovalWorkflowDefinitionRequestRelationshipsValue,
        >,
    >,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<crate::models::BulkWritableCableRequestStatus>>,
}

impl CloudResourceTypeRequest {
    /// Base class to use for serializers based on OrganizationalModel or PrimaryModel.  Can also be used for models derived from BaseModel, so long as they support custom fields, notes, and relationships.
    pub fn new(
        content_types: Vec<String>,
        name: String,
        provider: crate::models::BulkWritableCloudAccountRequestProvider,
    ) -> CloudResourceTypeRequest {
        CloudResourceTypeRequest {
            id: None,
            content_types,
            name,
            description: None,
            config_schema: None,
            provider: Box::new(provider),
            custom_fields: None,
            relationships: None,
            tags: None,
        }
    }
}
