/*
 * API Documentation
 *
 * Source of truth and network automation platform
 *
 * The version of the OpenAPI document: 2.4.20 (2.4)
 *
 * Generated by: https://openapi-generator.tech
 */

/// CloudServiceNetworkAssignment : Extends the built-in ModelSerializer to enforce calling full_clean() on a copy of the associated instance during validation. (DRF does not do this by default; see <https://github.com/encode/django-rest-framework/issues/3144>)

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CloudServiceNetworkAssignment {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<uuid::Uuid>,
    #[serde(rename = "object_type", skip_serializing_if = "Option::is_none")]
    pub object_type: Option<String>,
    /// Human friendly display value
    #[serde(rename = "display", skip_serializing_if = "Option::is_none")]
    pub display: Option<String>,
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    #[serde(rename = "natural_slug", skip_serializing_if = "Option::is_none")]
    pub natural_slug: Option<String>,
    #[serde(rename = "cloud_network")]
    pub cloud_network: Box<crate::models::BulkWritableCableRequestStatus>,
    #[serde(rename = "cloud_service")]
    pub cloud_service: Box<crate::models::BulkWritableCableRequestStatus>,
}

impl CloudServiceNetworkAssignment {
    /// Extends the built-in ModelSerializer to enforce calling full_clean() on a copy of the associated instance during validation. (DRF does not do this by default; see <https://github.com/encode/django-rest-framework/issues/3144>)
    pub fn new(
        cloud_network: crate::models::BulkWritableCableRequestStatus,
        cloud_service: crate::models::BulkWritableCableRequestStatus,
    ) -> CloudServiceNetworkAssignment {
        CloudServiceNetworkAssignment {
            id: None,
            object_type: None,
            display: None,
            url: None,
            natural_slug: None,
            cloud_network: Box::new(cloud_network),
            cloud_service: Box::new(cloud_service),
        }
    }
}
