/*
 * API Documentation
 *
 * Source of truth and network automation platform
 *
 * The version of the OpenAPI document: 2.4.20 (2.4)
 *
 * Generated by: https://openapi-generator.tech
 */

/// ControllerManagedDeviceGroupRadioProfileAssignmentRequest : Extends the built-in ModelSerializer to enforce calling full_clean() on a copy of the associated instance during validation. (DRF does not do this by default; see <https://github.com/encode/django-rest-framework/issues/3144>)

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ControllerManagedDeviceGroupRadioProfileAssignmentRequest {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<uuid::Uuid>,
    #[serde(rename = "controller_managed_device_group")]
    pub controller_managed_device_group: Box<crate::models::BulkWritableCableRequestStatus>,
    #[serde(rename = "radio_profile")]
    pub radio_profile: Box<crate::models::BulkWritableCableRequestStatus>,
}

impl ControllerManagedDeviceGroupRadioProfileAssignmentRequest {
    /// Extends the built-in ModelSerializer to enforce calling full_clean() on a copy of the associated instance during validation. (DRF does not do this by default; see <https://github.com/encode/django-rest-framework/issues/3144>)
    pub fn new(
        controller_managed_device_group: crate::models::BulkWritableCableRequestStatus,
        radio_profile: crate::models::BulkWritableCableRequestStatus,
    ) -> ControllerManagedDeviceGroupRadioProfileAssignmentRequest {
        ControllerManagedDeviceGroupRadioProfileAssignmentRequest {
            id: None,
            controller_managed_device_group: Box::new(controller_managed_device_group),
            radio_profile: Box::new(radio_profile),
        }
    }
}
