/*
 * API Documentation
 *
 * Source of truth and network automation platform
 *
 * The version of the OpenAPI document: 2.4.20 (2.4)
 *
 * Generated by: https://openapi-generator.tech
 */

/// Device : Base class to use for serializers based on OrganizationalModel or PrimaryModel.  Can also be used for models derived from BaseModel, so long as they support custom fields, notes, and relationships.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Device {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<uuid::Uuid>,
    #[serde(rename = "object_type", skip_serializing_if = "Option::is_none")]
    pub object_type: Option<String>,
    /// Human friendly display value
    #[serde(rename = "display", skip_serializing_if = "Option::is_none")]
    pub display: Option<String>,
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    #[serde(rename = "natural_slug", skip_serializing_if = "Option::is_none")]
    pub natural_slug: Option<String>,
    #[serde(rename = "face", skip_serializing_if = "Option::is_none")]
    pub face: Option<Box<crate::models::DeviceFace>>,
    #[serde(
        rename = "local_config_context_data",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub local_config_context_data: Option<Option<serde_json::Value>>,
    #[serde(
        rename = "local_config_context_data_owner_object_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub local_config_context_data_owner_object_id: Option<Option<uuid::Uuid>>,
    #[serde(
        rename = "name",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub name: Option<Option<String>>,
    #[serde(rename = "serial", skip_serializing_if = "Option::is_none")]
    pub serial: Option<String>,
    /// A unique tag used to identify this device
    #[serde(
        rename = "asset_tag",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub asset_tag: Option<Option<String>>,
    /// The lowest-numbered unit occupied by the device
    #[serde(
        rename = "position",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub position: Option<Option<i32>>,
    /// The priority the device has in the device redundancy group.
    #[serde(
        rename = "device_redundancy_group_priority",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub device_redundancy_group_priority: Option<Option<i32>>,
    #[serde(
        rename = "vc_position",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub vc_position: Option<Option<i32>>,
    #[serde(
        rename = "vc_priority",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub vc_priority: Option<Option<i32>>,
    #[serde(rename = "comments", skip_serializing_if = "Option::is_none")]
    pub comments: Option<String>,
    #[serde(
        rename = "local_config_context_schema",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub local_config_context_schema:
        Option<Option<Box<crate::models::BulkWritableConfigContextRequestConfigContextSchema>>>,
    #[serde(
        rename = "local_config_context_data_owner_content_type",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub local_config_context_data_owner_content_type:
        Option<Option<Box<crate::models::BulkWritableCircuitRequestTenant>>>,
    #[serde(rename = "device_type")]
    pub device_type: Box<crate::models::BulkWritableCableRequestStatus>,
    #[serde(rename = "status")]
    pub status: Box<crate::models::BulkWritableCableRequestStatus>,
    #[serde(rename = "role")]
    pub role: Box<crate::models::BulkWritableCableRequestStatus>,
    #[serde(
        rename = "tenant",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub tenant: Option<Option<Box<crate::models::BulkWritableCircuitRequestTenant>>>,
    #[serde(
        rename = "platform",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub platform: Option<Option<Box<crate::models::BulkWritableCircuitRequestTenant>>>,
    #[serde(rename = "location")]
    pub location: Box<crate::models::BulkWritableCableRequestStatus>,
    #[serde(
        rename = "rack",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub rack: Option<Option<Box<crate::models::BulkWritableCircuitRequestTenant>>>,
    #[serde(
        rename = "primary_ip4",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub primary_ip4: Option<Option<Box<crate::models::PrimaryIpv4>>>,
    #[serde(
        rename = "primary_ip6",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub primary_ip6: Option<Option<Box<crate::models::PrimaryIpv6>>>,
    #[serde(
        rename = "cluster",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub cluster: Option<Option<Box<crate::models::BulkWritableCircuitRequestTenant>>>,
    #[serde(
        rename = "virtual_chassis",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub virtual_chassis: Option<Option<Box<crate::models::BulkWritableCircuitRequestTenant>>>,
    #[serde(
        rename = "device_redundancy_group",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub device_redundancy_group:
        Option<Option<Box<crate::models::BulkWritableCircuitRequestTenant>>>,
    #[serde(
        rename = "software_version",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub software_version:
        Option<Option<Box<crate::models::BulkWritableDeviceRequestSoftwareVersion>>>,
    #[serde(
        rename = "secrets_group",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub secrets_group: Option<Option<Box<crate::models::BulkWritableCircuitRequestTenant>>>,
    #[serde(
        rename = "controller_managed_device_group",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub controller_managed_device_group:
        Option<Option<Box<crate::models::BulkWritableCircuitRequestTenant>>>,
    /// Override the software image files associated with the software version for this device
    #[serde(
        rename = "software_image_files",
        skip_serializing_if = "Option::is_none"
    )]
    pub software_image_files: Option<Vec<crate::models::SoftwareImageFiles>>,
    #[serde(
        rename = "created",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub created: Option<Option<String>>,
    #[serde(
        rename = "last_updated",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub last_updated: Option<Option<String>>,
    #[serde(rename = "notes_url", skip_serializing_if = "Option::is_none")]
    pub notes_url: Option<String>,
    #[serde(rename = "custom_fields", skip_serializing_if = "Option::is_none")]
    pub custom_fields: Option<::std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<crate::models::BulkWritableCableRequestStatus>>,
    #[serde(
        rename = "parent_bay",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub parent_bay: Option<Option<Box<crate::models::BulkWritableCircuitRequestTenant>>>,
}

impl Device {
    /// Base class to use for serializers based on OrganizationalModel or PrimaryModel.  Can also be used for models derived from BaseModel, so long as they support custom fields, notes, and relationships.
    pub fn new(
        device_type: crate::models::BulkWritableCableRequestStatus,
        status: crate::models::BulkWritableCableRequestStatus,
        role: crate::models::BulkWritableCableRequestStatus,
        location: crate::models::BulkWritableCableRequestStatus,
    ) -> Device {
        Device {
            id: None,
            object_type: None,
            display: None,
            url: None,
            natural_slug: None,
            face: None,
            local_config_context_data: None,
            local_config_context_data_owner_object_id: None,
            name: None,
            serial: None,
            asset_tag: None,
            position: None,
            device_redundancy_group_priority: None,
            vc_position: None,
            vc_priority: None,
            comments: None,
            local_config_context_schema: None,
            local_config_context_data_owner_content_type: None,
            device_type: Box::new(device_type),
            status: Box::new(status),
            role: Box::new(role),
            tenant: None,
            platform: None,
            location: Box::new(location),
            rack: None,
            primary_ip4: None,
            primary_ip6: None,
            cluster: None,
            virtual_chassis: None,
            device_redundancy_group: None,
            software_version: None,
            secrets_group: None,
            controller_managed_device_group: None,
            software_image_files: None,
            created: None,
            last_updated: None,
            notes_url: None,
            custom_fields: None,
            tags: None,
            parent_bay: None,
        }
    }
}
