/*
 * API Documentation
 *
 * Source of truth and network automation platform
 *
 * The version of the OpenAPI document: 2.4.20 (2.4)
 *
 * Generated by: https://openapi-generator.tech
 */

/// DynamicGroupMembership : Extends the built-in ModelSerializer to enforce calling full_clean() on a copy of the associated instance during validation. (DRF does not do this by default; see <https://github.com/encode/django-rest-framework/issues/3144>)

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DynamicGroupMembership {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<uuid::Uuid>,
    #[serde(rename = "object_type", skip_serializing_if = "Option::is_none")]
    pub object_type: Option<String>,
    /// Human friendly display value
    #[serde(rename = "display", skip_serializing_if = "Option::is_none")]
    pub display: Option<String>,
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    #[serde(rename = "natural_slug", skip_serializing_if = "Option::is_none")]
    pub natural_slug: Option<String>,
    #[serde(rename = "operator")]
    pub operator: crate::models::OperatorEnum,
    #[serde(rename = "weight")]
    pub weight: i32,
    #[serde(rename = "group")]
    pub group: Box<crate::models::BulkWritableCableRequestStatus>,
    #[serde(rename = "parent_group")]
    pub parent_group: Box<crate::models::BulkWritableCableRequestStatus>,
}

impl DynamicGroupMembership {
    /// Extends the built-in ModelSerializer to enforce calling full_clean() on a copy of the associated instance during validation. (DRF does not do this by default; see <https://github.com/encode/django-rest-framework/issues/3144>)
    pub fn new(
        operator: crate::models::OperatorEnum,
        weight: i32,
        group: crate::models::BulkWritableCableRequestStatus,
        parent_group: crate::models::BulkWritableCableRequestStatus,
    ) -> DynamicGroupMembership {
        DynamicGroupMembership {
            id: None,
            object_type: None,
            display: None,
            url: None,
            natural_slug: None,
            operator,
            weight,
            group: Box::new(group),
            parent_group: Box::new(parent_group),
        }
    }
}
