/*
 * API Documentation
 *
 * Source of truth and network automation platform
 *
 * The version of the OpenAPI document: 3.1.3 (3.1)
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ExtrasSecretsCheckRetrieve200Response {
    #[serde(rename = "result", skip_serializing_if = "Option::is_none")]
    pub result: Option<bool>,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

impl ExtrasSecretsCheckRetrieve200Response {
    pub fn new() -> ExtrasSecretsCheckRetrieve200Response {
        ExtrasSecretsCheckRetrieve200Response {
            result: None,
            message: None,
        }
    }
}
