/*
 * API Documentation
 *
 * Source of truth and network automation platform
 *
 * The version of the OpenAPI document: 2.4.20 (2.4)
 *
 * Generated by: https://openapi-generator.tech
 */

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum FaceEnum {
    #[serde(rename = "front")]
    Front,
    #[serde(rename = "rear")]
    Rear,
}

impl ToString for FaceEnum {
    fn to_string(&self) -> String {
        match self {
            Self::Front => String::from("front"),
            Self::Rear => String::from("rear"),
        }
    }
}

impl Default for FaceEnum {
    fn default() -> FaceEnum {
        Self::Front
    }
}
