/*
 * API Documentation
 *
 * Source of truth and network automation platform
 *
 * The version of the OpenAPI document: 2.4.20 (2.4)
 *
 * Generated by: https://openapi-generator.tech
 */

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum FilterLogicEnum {
    #[serde(rename = "disabled")]
    Disabled,
    #[serde(rename = "loose")]
    Loose,
    #[serde(rename = "exact")]
    Exact,
}

impl ToString for FilterLogicEnum {
    fn to_string(&self) -> String {
        match self {
            Self::Disabled => String::from("disabled"),
            Self::Loose => String::from("loose"),
            Self::Exact => String::from("exact"),
        }
    }
}

impl Default for FilterLogicEnum {
    fn default() -> FilterLogicEnum {
        Self::Disabled
    }
}
