/*
 * API Documentation
 *
 * Source of truth and network automation platform
 *
 * The version of the OpenAPI document: 2.4.20 (2.4)
 *
 * Generated by: https://openapi-generator.tech
 */

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum FrequencyEnum {
    #[serde(rename = "2.4GHz")]
    Variant2Period4Ghz,
    #[serde(rename = "5GHz")]
    Variant5Ghz,
    #[serde(rename = "6GHz")]
    Variant6Ghz,
}

impl ToString for FrequencyEnum {
    fn to_string(&self) -> String {
        match self {
            Self::Variant2Period4Ghz => String::from("2.4GHz"),
            Self::Variant5Ghz => String::from("5GHz"),
            Self::Variant6Ghz => String::from("6GHz"),
        }
    }
}

impl Default for FrequencyEnum {
    fn default() -> FrequencyEnum {
        Self::Variant2Period4Ghz
    }
}
