/*
 * API Documentation
 *
 * Source of truth and network automation platform
 *
 * The version of the OpenAPI document: 3.1.3 (3.1)
 *
 * Generated by: https://openapi-generator.tech
 */

/// GitRepositorySyncResponse : Serializer representing responses from the GitRepository.sync() POST endpoint.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GitRepositorySyncResponse {
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    #[serde(rename = "job_result", skip_serializing_if = "Option::is_none")]
    pub job_result: Option<Box<crate::models::JobResult>>,
}

impl GitRepositorySyncResponse {
    /// Serializer representing responses from the GitRepository.sync() POST endpoint.
    pub fn new() -> GitRepositorySyncResponse {
        GitRepositorySyncResponse {
            message: None,
            job_result: None,
        }
    }
}
