/*
 * API Documentation
 *
 * Source of truth and network automation platform
 *
 * The version of the OpenAPI document: 2.4.20 (2.4)
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GraphQlQueryInputRequest {
    #[serde(
        rename = "variables",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub variables: Option<Option<::std::collections::HashMap<String, serde_json::Value>>>,
}

impl GraphQlQueryInputRequest {
    pub fn new() -> GraphQlQueryInputRequest {
        GraphQlQueryInputRequest { variables: None }
    }
}
