/*
 * API Documentation
 *
 * Source of truth and network automation platform
 *
 * The version of the OpenAPI document: 2.4.20 (2.4)
 *
 * Generated by: https://openapi-generator.tech
 */

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum GroupTypeEnum {
    #[serde(rename = "dynamic-filter")]
    DynamicFilter,
    #[serde(rename = "dynamic-set")]
    DynamicSet,
    #[serde(rename = "static")]
    Static,
}

impl ToString for GroupTypeEnum {
    fn to_string(&self) -> String {
        match self {
            Self::DynamicFilter => String::from("dynamic-filter"),
            Self::DynamicSet => String::from("dynamic-set"),
            Self::Static => String::from("static"),
        }
    }
}

impl Default for GroupTypeEnum {
    fn default() -> GroupTypeEnum {
        Self::DynamicFilter
    }
}
