/*
 * API Documentation
 *
 * Source of truth and network automation platform
 *
 * The version of the OpenAPI document: 3.1.3 (3.1)
 *
 * Generated by: https://openapi-generator.tech
 */

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum IntegrityAlgorithmEnum {
    #[serde(rename = "MD5")]
    Md5,
    #[serde(rename = "SHA1")]
    Sha1,
    #[serde(rename = "SHA256")]
    Sha256,
    #[serde(rename = "SHA384")]
    Sha384,
    #[serde(rename = "SHA512")]
    Sha512,
}

impl ToString for IntegrityAlgorithmEnum {
    fn to_string(&self) -> String {
        match self {
            Self::Md5 => String::from("MD5"),
            Self::Sha1 => String::from("SHA1"),
            Self::Sha256 => String::from("SHA256"),
            Self::Sha384 => String::from("SHA384"),
            Self::Sha512 => String::from("SHA512"),
        }
    }
}

impl Default for IntegrityAlgorithmEnum {
    fn default() -> IntegrityAlgorithmEnum {
        Self::Md5
    }
}
