/*
 * API Documentation
 *
 * Source of truth and network automation platform
 *
 * The version of the OpenAPI document: 2.4.20 (2.4)
 *
 * Generated by: https://openapi-generator.tech
 */

/// Interface : Base class to use for serializers based on OrganizationalModel or PrimaryModel.  Can also be used for models derived from BaseModel, so long as they support custom fields, notes, and relationships.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Interface {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<uuid::Uuid>,
    #[serde(rename = "object_type", skip_serializing_if = "Option::is_none")]
    pub object_type: Option<String>,
    /// Human friendly display value
    #[serde(rename = "display", skip_serializing_if = "Option::is_none")]
    pub display: Option<String>,
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    #[serde(
        rename = "cable_peer_type",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub cable_peer_type: Option<Option<String>>,
    #[serde(
        rename = "cable_peer",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub cable_peer: Option<Option<Box<crate::models::CableTermination>>>,
    #[serde(rename = "natural_slug", skip_serializing_if = "Option::is_none")]
    pub natural_slug: Option<String>,
    #[serde(
        rename = "connected_endpoint_type",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub connected_endpoint_type: Option<Option<String>>,
    #[serde(
        rename = "connected_endpoint",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub connected_endpoint: Option<Option<Box<crate::models::PathEndpoint>>>,
    #[serde(
        rename = "connected_endpoint_reachable",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub connected_endpoint_reachable: Option<Option<bool>>,
    #[serde(rename = "type")]
    pub r#type: Box<crate::models::InterfaceType>,
    #[serde(rename = "mode", skip_serializing_if = "Option::is_none")]
    pub mode: Option<Box<crate::models::InterfaceMode>>,
    #[serde(
        rename = "mac_address",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub mac_address: Option<Option<String>>,
    #[serde(rename = "ip_address_count", skip_serializing_if = "Option::is_none")]
    pub ip_address_count: Option<i32>,
    #[serde(rename = "name")]
    pub name: String,
    /// Physical label
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
    #[serde(
        rename = "mtu",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub mtu: Option<Option<i32>>,
    /// This interface is used only for out-of-band management
    #[serde(rename = "mgmt_only", skip_serializing_if = "Option::is_none")]
    pub mgmt_only: Option<bool>,
    #[serde(
        rename = "device",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub device: Option<Option<Box<crate::models::BulkWritableCircuitRequestTenant>>>,
    #[serde(
        rename = "module",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub module: Option<Option<Box<crate::models::BulkWritableCircuitRequestTenant>>>,
    #[serde(
        rename = "cable",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub cable: Option<Option<Box<crate::models::CircuitCircuitTerminationA>>>,
    #[serde(rename = "status")]
    pub status: Box<crate::models::BulkWritableCableRequestStatus>,
    #[serde(
        rename = "role",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub role: Option<Option<Box<crate::models::BulkWritableCircuitRequestTenant>>>,
    #[serde(
        rename = "parent_interface",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub parent_interface:
        Option<Option<Box<crate::models::BulkWritableInterfaceRequestParentInterface>>>,
    #[serde(
        rename = "bridge",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub bridge: Option<Option<Box<crate::models::BridgeInterface>>>,
    #[serde(
        rename = "lag",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub lag: Option<Option<Box<crate::models::ParentLag>>>,
    #[serde(
        rename = "untagged_vlan",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub untagged_vlan: Option<Option<Box<crate::models::BulkWritableCircuitRequestTenant>>>,
    #[serde(
        rename = "vrf",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub vrf: Option<Option<Box<crate::models::BulkWritableCircuitRequestTenant>>>,
    #[serde(rename = "tagged_vlans", skip_serializing_if = "Option::is_none")]
    pub tagged_vlans: Option<Vec<crate::models::TaggedVlans>>,
    #[serde(rename = "ip_addresses", skip_serializing_if = "Option::is_none")]
    pub ip_addresses: Option<Vec<crate::models::IpAddresses>>,
    #[serde(
        rename = "created",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub created: Option<Option<String>>,
    #[serde(
        rename = "last_updated",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub last_updated: Option<Option<String>>,
    #[serde(rename = "notes_url", skip_serializing_if = "Option::is_none")]
    pub notes_url: Option<String>,
    #[serde(rename = "custom_fields", skip_serializing_if = "Option::is_none")]
    pub custom_fields: Option<::std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<crate::models::BulkWritableCableRequestStatus>>,
}

impl Interface {
    /// Base class to use for serializers based on OrganizationalModel or PrimaryModel.  Can also be used for models derived from BaseModel, so long as they support custom fields, notes, and relationships.
    pub fn new(
        r#type: crate::models::InterfaceType,
        name: String,
        status: crate::models::BulkWritableCableRequestStatus,
    ) -> Interface {
        Interface {
            id: None,
            object_type: None,
            display: None,
            url: None,
            cable_peer_type: None,
            cable_peer: None,
            natural_slug: None,
            connected_endpoint_type: None,
            connected_endpoint: None,
            connected_endpoint_reachable: None,
            r#type: Box::new(r#type),
            mode: None,
            mac_address: None,
            ip_address_count: None,
            name,
            label: None,
            description: None,
            enabled: None,
            mtu: None,
            mgmt_only: None,
            device: None,
            module: None,
            cable: None,
            status: Box::new(status),
            role: None,
            parent_interface: None,
            bridge: None,
            lag: None,
            untagged_vlan: None,
            vrf: None,
            tagged_vlans: None,
            ip_addresses: None,
            created: None,
            last_updated: None,
            notes_url: None,
            custom_fields: None,
            tags: None,
        }
    }
}
