/*
 * API Documentation
 *
 * Source of truth and network automation platform
 *
 * The version of the OpenAPI document: 3.2.4 (3.2)
 *
 * Generated by: https://openapi-generator.tech
 */

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum JobStatusEnum {
    #[serde(rename = "RUNNING")]
    Running,
    #[serde(rename = "NOT RUNNING")]
    NotRunning,
    #[serde(rename = "UNKNOWN")]
    Unknown,
    #[serde(rename = "RETRY")]
    Retry,
    #[serde(rename = "RECEIVED")]
    Received,
    #[serde(rename = "STARTED")]
    Started,
    #[serde(rename = "PENDING")]
    Pending,
    #[serde(rename = "SUCCESS")]
    Success,
    #[serde(rename = "REVOKED")]
    Revoked,
    #[serde(rename = "FAILURE")]
    Failure,
}

impl ToString for JobStatusEnum {
    fn to_string(&self) -> String {
        match self {
            Self::Running => String::from("RUNNING"),
            Self::NotRunning => String::from("NOT RUNNING"),
            Self::Unknown => String::from("UNKNOWN"),
            Self::Retry => String::from("RETRY"),
            Self::Received => String::from("RECEIVED"),
            Self::Started => String::from("STARTED"),
            Self::Pending => String::from("PENDING"),
            Self::Success => String::from("SUCCESS"),
            Self::Revoked => String::from("REVOKED"),
            Self::Failure => String::from("FAILURE"),
        }
    }
}

impl Default for JobStatusEnum {
    fn default() -> JobStatusEnum {
        Self::Running
    }
}
