/*
 * API Documentation
 *
 * Source of truth and network automation platform
 *
 * The version of the OpenAPI document: 3.1.0 (3.1)
 *
 * Generated by: https://openapi-generator.tech
 */

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum LoadBalancerTypeEnum {
    #[serde(rename = "layer2")]
    Layer2,
    #[serde(rename = "layer4")]
    Layer4,
    #[serde(rename = "layer7")]
    Layer7,
    #[serde(rename = "dns")]
    Dns,
}

impl ToString for LoadBalancerTypeEnum {
    fn to_string(&self) -> String {
        match self {
            Self::Layer2 => String::from("layer2"),
            Self::Layer4 => String::from("layer4"),
            Self::Layer7 => String::from("layer7"),
            Self::Dns => String::from("dns"),
        }
    }
}

impl Default for LoadBalancerTypeEnum {
    fn default() -> LoadBalancerTypeEnum {
        Self::Layer2
    }
}
