/*
 * API Documentation
 *
 * Source of truth and network automation platform
 *
 * The version of the OpenAPI document: 3.2.2 (3.2)
 *
 * Generated by: https://openapi-generator.tech
 */

/// NestedVpnTunnelEndpoint : VPNTunnelEndpoint Serializer.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct NestedVpnTunnelEndpoint {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<uuid::Uuid>,
    #[serde(rename = "object_type", skip_serializing_if = "Option::is_none")]
    pub object_type: Option<String>,
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
}

impl NestedVpnTunnelEndpoint {
    /// VPNTunnelEndpoint Serializer.
    pub fn new() -> NestedVpnTunnelEndpoint {
        NestedVpnTunnelEndpoint {
            id: None,
            object_type: None,
            url: None,
        }
    }
}
