/*
 * API Documentation
 *
 * Source of truth and network automation platform
 *
 * The version of the OpenAPI document: 3.1.2 (3.1)
 *
 * Generated by: https://openapi-generator.tech
 */

/// NestedCertificateProfile : CertificateProfile Serializer.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct NestedCertificateProfile {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<uuid::Uuid>,
    #[serde(rename = "object_type", skip_serializing_if = "Option::is_none")]
    pub object_type: Option<String>,
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
}

impl NestedCertificateProfile {
    /// CertificateProfile Serializer.
    pub fn new() -> NestedCertificateProfile {
        NestedCertificateProfile {
            id: None,
            object_type: None,
            url: None,
        }
    }
}
