/*
 * API Documentation
 *
 * Source of truth and network automation platform
 *
 * The version of the OpenAPI document: 2.4.20 (2.4)
 *
 * Generated by: https://openapi-generator.tech
 */

/// ParentChildStatus : Parent devices house child devices in device bays. Leave blank if this device type is neither a parent nor a child.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ParentChildStatus {}

impl ParentChildStatus {
    /// Parent devices house child devices in device bays. Leave blank if this device type is neither a parent nor a child.
    pub fn new() -> ParentChildStatus {
        ParentChildStatus {}
    }
}
