/*
 * API Documentation
 *
 * Source of truth and network automation platform
 *
 * The version of the OpenAPI document: 3.1.0 (3.1)
 *
 * Generated by: https://openapi-generator.tech
 */

/// ParentLag : Assigned LAG interface

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ParentLag {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<Box<crate::models::ApprovalWorkflowApprovalWorkflowDefinitionId>>,
    #[serde(rename = "object_type", skip_serializing_if = "Option::is_none")]
    pub object_type: Option<String>,
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
}

impl ParentLag {
    /// Assigned LAG interface
    pub fn new() -> ParentLag {
        ParentLag {
            id: None,
            object_type: None,
            url: None,
        }
    }
}
