/*
 * API Documentation
 *
 * Source of truth and network automation platform
 *
 * The version of the OpenAPI document: 2.4.20 (2.4)
 *
 * Generated by: https://openapi-generator.tech
 */

/// PatchedComputedFieldRequest : Extends the built-in ModelSerializer to enforce calling full_clean() on a copy of the associated instance during validation. (DRF does not do this by default; see <https://github.com/encode/django-rest-framework/issues/3144>)

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PatchedComputedFieldRequest {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<uuid::Uuid>,
    #[serde(rename = "content_type", skip_serializing_if = "Option::is_none")]
    pub content_type: Option<String>,
    /// Internal field name. Please use underscores rather than dashes in this key.
    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    /// Human-readable grouping that this computed field belongs to.
    #[serde(rename = "grouping", skip_serializing_if = "Option::is_none")]
    pub grouping: Option<String>,
    /// Name of the field as displayed to users
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Jinja2 template code for field value
    #[serde(rename = "template", skip_serializing_if = "Option::is_none")]
    pub template: Option<String>,
    /// Fallback value (if any) to be output for the field in the case of a template rendering error.
    #[serde(rename = "fallback_value", skip_serializing_if = "Option::is_none")]
    pub fallback_value: Option<String>,
    #[serde(rename = "weight", skip_serializing_if = "Option::is_none")]
    pub weight: Option<i32>,
    /// Hide this field from the object's primary information tab. It will appear in the \"Advanced\" tab instead.
    #[serde(rename = "advanced_ui", skip_serializing_if = "Option::is_none")]
    pub advanced_ui: Option<bool>,
}

impl PatchedComputedFieldRequest {
    /// Extends the built-in ModelSerializer to enforce calling full_clean() on a copy of the associated instance during validation. (DRF does not do this by default; see <https://github.com/encode/django-rest-framework/issues/3144>)
    pub fn new() -> PatchedComputedFieldRequest {
        PatchedComputedFieldRequest {
            id: None,
            content_type: None,
            key: None,
            grouping: None,
            label: None,
            description: None,
            template: None,
            fallback_value: None,
            weight: None,
            advanced_ui: None,
        }
    }
}
