/*
 * API Documentation
 *
 * Source of truth and network automation platform
 *
 * The version of the OpenAPI document: 3.2.2 (3.2)
 *
 * Generated by: https://openapi-generator.tech
 */

/// PatchedBulkWritableVirtualServerCertificateProfileAssignmentRequest : VirtualServerCertificateProfileAssignment Serializer.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PatchedBulkWritableVirtualServerCertificateProfileAssignmentRequest {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "virtual_server", skip_serializing_if = "Option::is_none")]
    pub virtual_server: Option<Box<crate::models::BulkWritableCableRequestStatus>>,
    #[serde(
        rename = "certificate_profile",
        skip_serializing_if = "Option::is_none"
    )]
    pub certificate_profile: Option<Box<crate::models::BulkWritableCableRequestStatus>>,
}

impl PatchedBulkWritableVirtualServerCertificateProfileAssignmentRequest {
    /// VirtualServerCertificateProfileAssignment Serializer.
    pub fn new(
        id: uuid::Uuid,
    ) -> PatchedBulkWritableVirtualServerCertificateProfileAssignmentRequest {
        PatchedBulkWritableVirtualServerCertificateProfileAssignmentRequest {
            id,
            virtual_server: None,
            certificate_profile: None,
        }
    }
}
