/*
 * API Documentation
 *
 * Source of truth and network automation platform
 *
 * The version of the OpenAPI document: 3.2.6 (3.2)
 *
 * Generated by: https://openapi-generator.tech
 */

/// PatchedVpnProfilePhase1PolicyAssignmentRequest : Serializer for `VPNProfilePhase1PolicyAssignment` objects.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PatchedVpnProfilePhase1PolicyAssignmentRequest {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<uuid::Uuid>,
    /// Higher weights appear later in the list
    #[serde(rename = "weight", skip_serializing_if = "Option::is_none")]
    pub weight: Option<i32>,
    #[serde(rename = "vpn_profile", skip_serializing_if = "Option::is_none")]
    pub vpn_profile: Option<Box<crate::models::BulkWritableCableRequestStatus>>,
    #[serde(rename = "vpn_phase1_policy", skip_serializing_if = "Option::is_none")]
    pub vpn_phase1_policy: Option<Box<crate::models::BulkWritableCableRequestStatus>>,
}

impl PatchedVpnProfilePhase1PolicyAssignmentRequest {
    /// Serializer for `VPNProfilePhase1PolicyAssignment` objects.
    pub fn new() -> PatchedVpnProfilePhase1PolicyAssignmentRequest {
        PatchedVpnProfilePhase1PolicyAssignmentRequest {
            id: None,
            weight: None,
            vpn_profile: None,
            vpn_phase1_policy: None,
        }
    }
}
