/*
 * API Documentation
 *
 * Source of truth and network automation platform
 *
 * The version of the OpenAPI document: 3.1.0 (3.1)
 *
 * Generated by: https://openapi-generator.tech
 */

/// PatchedWritableConsolePortRequestType : Physical port type

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PatchedWritableConsolePortRequestType {}

impl PatchedWritableConsolePortRequestType {
    /// Physical port type
    pub fn new() -> PatchedWritableConsolePortRequestType {
        PatchedWritableConsolePortRequestType {}
    }
}
