/*
 * API Documentation
 *
 * Source of truth and network automation platform
 *
 * The version of the OpenAPI document: 3.2.2 (3.2)
 *
 * Generated by: https://openapi-generator.tech
 */

/// PatchedBulkWritableNoteRequest : Extends the built-in ModelSerializer to enforce calling full_clean() on a copy of the associated instance during validation. (DRF does not do this by default; see <https://github.com/encode/django-rest-framework/issues/3144>)

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PatchedBulkWritableNoteRequest {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(
        rename = "assigned_object_type",
        skip_serializing_if = "Option::is_none"
    )]
    pub assigned_object_type: Option<String>,
    #[serde(rename = "assigned_object_id", skip_serializing_if = "Option::is_none")]
    pub assigned_object_id: Option<uuid::Uuid>,
    #[serde(rename = "note", skip_serializing_if = "Option::is_none")]
    pub note: Option<String>,
    #[serde(
        rename = "user",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub user: Option<Option<Box<crate::models::ApprovalWorkflowUser>>>,
}

impl PatchedBulkWritableNoteRequest {
    /// Extends the built-in ModelSerializer to enforce calling full_clean() on a copy of the associated instance during validation. (DRF does not do this by default; see <https://github.com/encode/django-rest-framework/issues/3144>)
    pub fn new(id: uuid::Uuid) -> PatchedBulkWritableNoteRequest {
        PatchedBulkWritableNoteRequest {
            id,
            assigned_object_type: None,
            assigned_object_id: None,
            note: None,
            user: None,
        }
    }
}
