/*
 * API Documentation
 *
 * Source of truth and network automation platform
 *
 * The version of the OpenAPI document: 2.4.20 (2.4)
 *
 * Generated by: https://openapi-generator.tech
 */

/// PatchedBulkWritableControllerManagedDeviceGroupRadioProfileAssignmentRequest : Extends the built-in ModelSerializer to enforce calling full_clean() on a copy of the associated instance during validation. (DRF does not do this by default; see <https://github.com/encode/django-rest-framework/issues/3144>)

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PatchedBulkWritableControllerManagedDeviceGroupRadioProfileAssignmentRequest {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(
        rename = "controller_managed_device_group",
        skip_serializing_if = "Option::is_none"
    )]
    pub controller_managed_device_group: Option<Box<crate::models::BulkWritableCableRequestStatus>>,
    #[serde(rename = "radio_profile", skip_serializing_if = "Option::is_none")]
    pub radio_profile: Option<Box<crate::models::BulkWritableCableRequestStatus>>,
}

impl PatchedBulkWritableControllerManagedDeviceGroupRadioProfileAssignmentRequest {
    /// Extends the built-in ModelSerializer to enforce calling full_clean() on a copy of the associated instance during validation. (DRF does not do this by default; see <https://github.com/encode/django-rest-framework/issues/3144>)
    pub fn new(
        id: uuid::Uuid,
    ) -> PatchedBulkWritableControllerManagedDeviceGroupRadioProfileAssignmentRequest {
        PatchedBulkWritableControllerManagedDeviceGroupRadioProfileAssignmentRequest {
            id,
            controller_managed_device_group: None,
            radio_profile: None,
        }
    }
}
