/*
 * API Documentation
 *
 * Source of truth and network automation platform
 *
 * The version of the OpenAPI document: 3.1.0 (3.1)
 *
 * Generated by: https://openapi-generator.tech
 */

/// PatchedVpnProfilePhase2PolicyAssignmentRequest : Serializer for `VPNProfilePhase2PolicyAssignment` objects.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PatchedVpnProfilePhase2PolicyAssignmentRequest {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<uuid::Uuid>,
    /// Higher weights appear later in the list
    #[serde(rename = "weight", skip_serializing_if = "Option::is_none")]
    pub weight: Option<i32>,
    #[serde(rename = "vpn_profile", skip_serializing_if = "Option::is_none")]
    pub vpn_profile: Option<Box<crate::models::ApprovalWorkflowStageResponseApprovalWorkflowStage>>,
    #[serde(rename = "vpn_phase2_policy", skip_serializing_if = "Option::is_none")]
    pub vpn_phase2_policy:
        Option<Box<crate::models::ApprovalWorkflowStageResponseApprovalWorkflowStage>>,
    #[serde(rename = "custom_fields", skip_serializing_if = "Option::is_none")]
    pub custom_fields: Option<::std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "relationships", skip_serializing_if = "Option::is_none")]
    pub relationships: Option<
        ::std::collections::HashMap<
            String,
            crate::models::ApprovalWorkflowDefinitionRequestRelationshipsValue,
        >,
    >,
}

impl PatchedVpnProfilePhase2PolicyAssignmentRequest {
    /// Serializer for `VPNProfilePhase2PolicyAssignment` objects.
    pub fn new() -> PatchedVpnProfilePhase2PolicyAssignmentRequest {
        PatchedVpnProfilePhase2PolicyAssignmentRequest {
            id: None,
            weight: None,
            vpn_profile: None,
            vpn_phase2_policy: None,
            custom_fields: None,
            relationships: None,
        }
    }
}
