/*
 * API Documentation
 *
 * Source of truth and network automation platform
 *
 * The version of the OpenAPI document: 3.1.2 (3.1)
 *
 * Generated by: https://openapi-generator.tech
 */

/// PatchedBulkWritableVpnPhase2PolicyRequest : VPNPhase2Policy Serializer.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PatchedBulkWritableVpnPhase2PolicyRequest {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(
        rename = "encryption_algorithm",
        skip_serializing_if = "Option::is_none"
    )]
    pub encryption_algorithm: Option<Vec<crate::models::EncryptionAlgorithmEnum>>,
    #[serde(
        rename = "integrity_algorithm",
        skip_serializing_if = "Option::is_none"
    )]
    pub integrity_algorithm: Option<Vec<crate::models::IntegrityAlgorithmEnum>>,
    #[serde(rename = "pfs_group", skip_serializing_if = "Option::is_none")]
    pub pfs_group: Option<Vec<crate::models::VpnPhase2PolicyChoices>>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(
        rename = "lifetime",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub lifetime: Option<Option<i32>>,
    #[serde(
        rename = "tenant",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub tenant: Option<Option<Box<crate::models::ApprovalWorkflowUser>>>,
    #[serde(rename = "custom_fields", skip_serializing_if = "Option::is_none")]
    pub custom_fields: Option<::std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "relationships", skip_serializing_if = "Option::is_none")]
    pub relationships: Option<
        ::std::collections::HashMap<
            String,
            crate::models::ApprovalWorkflowDefinitionRequestRelationshipsValue,
        >,
    >,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<crate::models::ApprovalWorkflowStageResponseApprovalWorkflowStage>>,
}

impl PatchedBulkWritableVpnPhase2PolicyRequest {
    /// VPNPhase2Policy Serializer.
    pub fn new(id: uuid::Uuid) -> PatchedBulkWritableVpnPhase2PolicyRequest {
        PatchedBulkWritableVpnPhase2PolicyRequest {
            id,
            encryption_algorithm: None,
            integrity_algorithm: None,
            pfs_group: None,
            name: None,
            description: None,
            lifetime: None,
            tenant: None,
            custom_fields: None,
            relationships: None,
            tags: None,
        }
    }
}
