/*
 * API Documentation
 *
 * Source of truth and network automation platform
 *
 * The version of the OpenAPI document: 3.2.6 (3.2)
 *
 * Generated by: https://openapi-generator.tech
 */

/// PatchedBulkWritableVpnProfilePhase2PolicyAssignmentRequest : Serializer for `VPNProfilePhase2PolicyAssignment` objects.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PatchedBulkWritableVpnProfilePhase2PolicyAssignmentRequest {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    /// Higher weights appear later in the list
    #[serde(rename = "weight", skip_serializing_if = "Option::is_none")]
    pub weight: Option<i32>,
    #[serde(rename = "vpn_profile", skip_serializing_if = "Option::is_none")]
    pub vpn_profile: Option<Box<crate::models::BulkWritableCableRequestStatus>>,
    #[serde(rename = "vpn_phase2_policy", skip_serializing_if = "Option::is_none")]
    pub vpn_phase2_policy: Option<Box<crate::models::BulkWritableCableRequestStatus>>,
}

impl PatchedBulkWritableVpnProfilePhase2PolicyAssignmentRequest {
    /// Serializer for `VPNProfilePhase2PolicyAssignment` objects.
    pub fn new(id: uuid::Uuid) -> PatchedBulkWritableVpnProfilePhase2PolicyAssignmentRequest {
        PatchedBulkWritableVpnProfilePhase2PolicyAssignmentRequest {
            id,
            weight: None,
            vpn_profile: None,
            vpn_phase2_policy: None,
        }
    }
}
