/*
 * API Documentation
 *
 * Source of truth and network automation platform
 *
 * The version of the OpenAPI document: 3.1.4 (3.1)
 *
 * Generated by: https://openapi-generator.tech
 */

/// PatchedBulkWritableInterfaceRedundancyGroupRequest : InterfaceRedundancyGroup Serializer.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PatchedBulkWritableInterfaceRedundancyGroupRequest {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "protocol", skip_serializing_if = "Option::is_none")]
    pub protocol: Option<crate::models::InterfaceRedundancyGroupProtocolChoices>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "protocol_group_id", skip_serializing_if = "Option::is_none")]
    pub protocol_group_id: Option<String>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<Box<crate::models::ApprovalWorkflowStageResponseApprovalWorkflowStage>>,
    #[serde(
        rename = "secrets_group",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub secrets_group: Option<Option<Box<crate::models::ApprovalWorkflowUser>>>,
    #[serde(
        rename = "virtual_ip",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub virtual_ip: Option<Option<Box<crate::models::ApprovalWorkflowUser>>>,
    #[serde(rename = "custom_fields", skip_serializing_if = "Option::is_none")]
    pub custom_fields: Option<::std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "relationships", skip_serializing_if = "Option::is_none")]
    pub relationships: Option<
        ::std::collections::HashMap<
            String,
            crate::models::ApprovalWorkflowDefinitionRequestRelationshipsValue,
        >,
    >,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<crate::models::ApprovalWorkflowStageResponseApprovalWorkflowStage>>,
}

impl PatchedBulkWritableInterfaceRedundancyGroupRequest {
    /// InterfaceRedundancyGroup Serializer.
    pub fn new(id: uuid::Uuid) -> PatchedBulkWritableInterfaceRedundancyGroupRequest {
        PatchedBulkWritableInterfaceRedundancyGroupRequest {
            id,
            protocol: None,
            name: None,
            description: None,
            protocol_group_id: None,
            status: None,
            secrets_group: None,
            virtual_ip: None,
            custom_fields: None,
            relationships: None,
            tags: None,
        }
    }
}
