/*
 * API Documentation
 *
 * Source of truth and network automation platform
 *
 * The version of the OpenAPI document: 2.4.20 (2.4)
 *
 * Generated by: https://openapi-generator.tech
 */

/// PatchedWritablePowerFeedRequestPowerPath : Physical power distribution redundancy path.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PatchedWritablePowerFeedRequestPowerPath {}

impl PatchedWritablePowerFeedRequestPowerPath {
    /// Physical power distribution redundancy path.
    pub fn new() -> PatchedWritablePowerFeedRequestPowerPath {
        PatchedWritablePowerFeedRequestPowerPath {}
    }
}
