/*
 * API Documentation
 *
 * Source of truth and network automation platform
 *
 * The version of the OpenAPI document: 2.4.20 (2.4)
 *
 * Generated by: https://openapi-generator.tech
 */

/// PatchedBulkWritableControllerManagedDeviceGroupWirelessNetworkAssignmentRequest : Extends the built-in ModelSerializer to enforce calling full_clean() on a copy of the associated instance during validation. (DRF does not do this by default; see <https://github.com/encode/django-rest-framework/issues/3144>)

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PatchedBulkWritableControllerManagedDeviceGroupWirelessNetworkAssignmentRequest {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(
        rename = "controller_managed_device_group",
        skip_serializing_if = "Option::is_none"
    )]
    pub controller_managed_device_group: Option<Box<crate::models::BulkWritableCableRequestStatus>>,
    #[serde(rename = "wireless_network", skip_serializing_if = "Option::is_none")]
    pub wireless_network: Option<Box<crate::models::BulkWritableCableRequestStatus>>,
    #[serde(
        rename = "vlan",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub vlan: Option<Option<Box<crate::models::BulkWritableCircuitRequestTenant>>>,
}

impl PatchedBulkWritableControllerManagedDeviceGroupWirelessNetworkAssignmentRequest {
    /// Extends the built-in ModelSerializer to enforce calling full_clean() on a copy of the associated instance during validation. (DRF does not do this by default; see <https://github.com/encode/django-rest-framework/issues/3144>)
    pub fn new(
        id: uuid::Uuid,
    ) -> PatchedBulkWritableControllerManagedDeviceGroupWirelessNetworkAssignmentRequest {
        PatchedBulkWritableControllerManagedDeviceGroupWirelessNetworkAssignmentRequest {
            id,
            controller_managed_device_group: None,
            wireless_network: None,
            vlan: None,
        }
    }
}
