/*
 * API Documentation
 *
 * Source of truth and network automation platform
 *
 * The version of the OpenAPI document: 2.4.20 (2.4)
 *
 * Generated by: https://openapi-generator.tech
 */

/// PatchedStaticGroupAssociationRequest : Base class to use for serializers based on OrganizationalModel or PrimaryModel.  Can also be used for models derived from BaseModel, so long as they support custom fields, notes, and relationships.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PatchedStaticGroupAssociationRequest {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<uuid::Uuid>,
    #[serde(
        rename = "associated_object_type",
        skip_serializing_if = "Option::is_none"
    )]
    pub associated_object_type: Option<String>,
    #[serde(
        rename = "associated_object_id",
        skip_serializing_if = "Option::is_none"
    )]
    pub associated_object_id: Option<uuid::Uuid>,
    #[serde(rename = "dynamic_group", skip_serializing_if = "Option::is_none")]
    pub dynamic_group: Option<Box<crate::models::BulkWritableCableRequestStatus>>,
    #[serde(rename = "custom_fields", skip_serializing_if = "Option::is_none")]
    pub custom_fields: Option<::std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "relationships", skip_serializing_if = "Option::is_none")]
    pub relationships: Option<
        ::std::collections::HashMap<
            String,
            crate::models::BulkWritableCableRequestRelationshipsValue,
        >,
    >,
}

impl PatchedStaticGroupAssociationRequest {
    /// Base class to use for serializers based on OrganizationalModel or PrimaryModel.  Can also be used for models derived from BaseModel, so long as they support custom fields, notes, and relationships.
    pub fn new() -> PatchedStaticGroupAssociationRequest {
        PatchedStaticGroupAssociationRequest {
            id: None,
            associated_object_type: None,
            associated_object_id: None,
            dynamic_group: None,
            custom_fields: None,
            relationships: None,
        }
    }
}
