/*
 * API Documentation
 *
 * Source of truth and network automation platform
 *
 * The version of the OpenAPI document: 3.2.2 (3.2)
 *
 * Generated by: https://openapi-generator.tech
 */

/// PatchedWritablePowerPortRequestType : Physical port type

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PatchedWritablePowerPortRequestType {}

impl PatchedWritablePowerPortRequestType {
    /// Physical port type
    pub fn new() -> PatchedWritablePowerPortRequestType {
        PatchedWritablePowerPortRequestType {}
    }
}
