/*
 * API Documentation
 *
 * Source of truth and network automation platform
 *
 * The version of the OpenAPI document: 3.1.6 (3.1)
 *
 * Generated by: https://openapi-generator.tech
 */

/// PatchedBulkWritableVrfPrefixAssignmentRequest : Extends the built-in ModelSerializer to enforce calling full_clean() on a copy of the associated instance during validation. (DRF does not do this by default; see <https://github.com/encode/django-rest-framework/issues/3144>)

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PatchedBulkWritableVrfPrefixAssignmentRequest {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "vrf", skip_serializing_if = "Option::is_none")]
    pub vrf: Option<Box<crate::models::ApprovalWorkflowStageResponseApprovalWorkflowStage>>,
    #[serde(rename = "prefix", skip_serializing_if = "Option::is_none")]
    pub prefix: Option<Box<crate::models::ApprovalWorkflowStageResponseApprovalWorkflowStage>>,
}

impl PatchedBulkWritableVrfPrefixAssignmentRequest {
    /// Extends the built-in ModelSerializer to enforce calling full_clean() on a copy of the associated instance during validation. (DRF does not do this by default; see <https://github.com/encode/django-rest-framework/issues/3144>)
    pub fn new(id: uuid::Uuid) -> PatchedBulkWritableVrfPrefixAssignmentRequest {
        PatchedBulkWritableVrfPrefixAssignmentRequest {
            id,
            vrf: None,
            prefix: None,
        }
    }
}
