/*
 * API Documentation
 *
 * Source of truth and network automation platform
 *
 * The version of the OpenAPI document: 3.1.0 (3.1)
 *
 * Generated by: https://openapi-generator.tech
 */

/// PatchedContactAssociationRequest : Base class to use for serializers based on OrganizationalModel or PrimaryModel.  Can also be used for models derived from BaseModel, so long as they support custom fields, notes, and relationships.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PatchedContactAssociationRequest {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<uuid::Uuid>,
    #[serde(
        rename = "associated_object_type",
        skip_serializing_if = "Option::is_none"
    )]
    pub associated_object_type: Option<String>,
    #[serde(
        rename = "associated_object_id",
        skip_serializing_if = "Option::is_none"
    )]
    pub associated_object_id: Option<uuid::Uuid>,
    #[serde(
        rename = "contact",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub contact: Option<Option<Box<crate::models::ApprovalWorkflowUser>>>,
    #[serde(
        rename = "team",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub team: Option<Option<Box<crate::models::ApprovalWorkflowUser>>>,
    #[serde(rename = "role", skip_serializing_if = "Option::is_none")]
    pub role: Option<Box<crate::models::ApprovalWorkflowStageResponseApprovalWorkflowStage>>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<Box<crate::models::ApprovalWorkflowStageResponseApprovalWorkflowStage>>,
    #[serde(rename = "custom_fields", skip_serializing_if = "Option::is_none")]
    pub custom_fields: Option<::std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "relationships", skip_serializing_if = "Option::is_none")]
    pub relationships: Option<
        ::std::collections::HashMap<
            String,
            crate::models::ApprovalWorkflowDefinitionRequestRelationshipsValue,
        >,
    >,
}

impl PatchedContactAssociationRequest {
    /// Base class to use for serializers based on OrganizationalModel or PrimaryModel.  Can also be used for models derived from BaseModel, so long as they support custom fields, notes, and relationships.
    pub fn new() -> PatchedContactAssociationRequest {
        PatchedContactAssociationRequest {
            id: None,
            associated_object_type: None,
            associated_object_id: None,
            contact: None,
            team: None,
            role: None,
            status: None,
            custom_fields: None,
            relationships: None,
        }
    }
}
