/*
 * API Documentation
 *
 * Source of truth and network automation platform
 *
 * The version of the OpenAPI document: 2.4.20 (2.4)
 *
 * Generated by: https://openapi-generator.tech
 */

/// PatchedDynamicGroupMembershipRequest : Extends the built-in ModelSerializer to enforce calling full_clean() on a copy of the associated instance during validation. (DRF does not do this by default; see <https://github.com/encode/django-rest-framework/issues/3144>)

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PatchedDynamicGroupMembershipRequest {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<uuid::Uuid>,
    #[serde(rename = "operator", skip_serializing_if = "Option::is_none")]
    pub operator: Option<crate::models::OperatorEnum>,
    #[serde(rename = "weight", skip_serializing_if = "Option::is_none")]
    pub weight: Option<i32>,
    #[serde(rename = "group", skip_serializing_if = "Option::is_none")]
    pub group: Option<Box<crate::models::BulkWritableCableRequestStatus>>,
    #[serde(rename = "parent_group", skip_serializing_if = "Option::is_none")]
    pub parent_group: Option<Box<crate::models::BulkWritableCableRequestStatus>>,
}

impl PatchedDynamicGroupMembershipRequest {
    /// Extends the built-in ModelSerializer to enforce calling full_clean() on a copy of the associated instance during validation. (DRF does not do this by default; see <https://github.com/encode/django-rest-framework/issues/3144>)
    pub fn new() -> PatchedDynamicGroupMembershipRequest {
        PatchedDynamicGroupMembershipRequest {
            id: None,
            operator: None,
            weight: None,
            group: None,
            parent_group: None,
        }
    }
}
