/*
 * API Documentation
 *
 * Source of truth and network automation platform
 *
 * The version of the OpenAPI document: 3.2.2 (3.2)
 *
 * Generated by: https://openapi-generator.tech
 */

/// PatchedWritableCableRequest : Schema-only variant of `CableSerializer` advertising the writable `terminations` payload.  The runtime `CableSerializer.terminations` field is a `SerializerMethodField` (for depth-aware reads), so drf-spectacular marks it `readOnly: true` by default. This subclass overrides the field with a writable JSON field purely so the OpenAPI request body schema for POST/PUT/PATCH on `/api/dcim/cables/` advertises `terminations` as writable, and documents its accepted shape.  Not used at runtime; referenced only from `@extend_schema_view` on `CableViewSet`.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PatchedWritableCableRequest {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<uuid::Uuid>,
    #[serde(
        rename = "termination_a_type",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub termination_a_type: Option<Option<String>>,
    #[serde(
        rename = "termination_b_type",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub termination_b_type: Option<Option<String>>,
    #[serde(
        rename = "termination_a_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub termination_a_id: Option<Option<uuid::Uuid>>,
    #[serde(
        rename = "termination_b_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub termination_b_id: Option<Option<uuid::Uuid>>,
    #[serde(rename = "length_unit", skip_serializing_if = "Option::is_none")]
    pub length_unit: Option<crate::models::LengthUnitEnum>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<crate::models::CableTypeChoices>,
    /// Terminations to apply, keyed by side ('a'/'b') plus 1-indexed connector number. A standard cable has one connector per side ('a1', 'b1'); higher connector numbers ('a2', 'b2', ...) apply only to breakout cables with multiple connectors per side. Each value is either `null` (delete the existing termination at this connector) or an `{\"object_type\": \"<app.model>\", \"id\": \"<uuid>\"}` reference to the termination to plug in. Connectors omitted from the payload are left untouched (PATCH-style merge semantics).
    #[serde(rename = "terminations", skip_serializing_if = "Option::is_none")]
    pub terminations: Option<
        ::std::collections::HashMap<
            String,
            crate::models::PatchedWritableCableRequestTerminationsValue,
        >,
    >,
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
    /// RGB color in hexadecimal (e.g. 00ff00)
    #[serde(rename = "color", skip_serializing_if = "Option::is_none")]
    pub color: Option<String>,
    #[serde(
        rename = "length",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub length: Option<Option<i32>>,
    #[serde(
        rename = "cable_type",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub cable_type: Option<Option<Box<crate::models::BulkWritableCableRequestCableType>>>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<Box<crate::models::BulkWritableCableRequestStatus>>,
    /// Custom field data for this object, keyed by each applicable Custom Field's `key`. Value types vary with the custom field's type (text, integer, boolean, date, URL, JSON, select, multi-select); undefined values are `null`. On write, the payload is merged with existing values (PATCH-style: keys omitted from the payload are left untouched), and keys that do not correspond to a defined custom field are ignored.
    #[serde(rename = "custom_fields", skip_serializing_if = "Option::is_none")]
    pub custom_fields: Option<::std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "relationships", skip_serializing_if = "Option::is_none")]
    pub relationships: Option<
        ::std::collections::HashMap<
            String,
            crate::models::ApprovalWorkflowDefinitionRequestRelationshipsValue,
        >,
    >,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<crate::models::BulkWritableCableRequestStatus>>,
}

impl PatchedWritableCableRequest {
    /// Schema-only variant of `CableSerializer` advertising the writable `terminations` payload.  The runtime `CableSerializer.terminations` field is a `SerializerMethodField` (for depth-aware reads), so drf-spectacular marks it `readOnly: true` by default. This subclass overrides the field with a writable JSON field purely so the OpenAPI request body schema for POST/PUT/PATCH on `/api/dcim/cables/` advertises `terminations` as writable, and documents its accepted shape.  Not used at runtime; referenced only from `@extend_schema_view` on `CableViewSet`.
    pub fn new() -> PatchedWritableCableRequest {
        PatchedWritableCableRequest {
            id: None,
            termination_a_type: None,
            termination_b_type: None,
            termination_a_id: None,
            termination_b_id: None,
            length_unit: None,
            r#type: None,
            terminations: None,
            label: None,
            color: None,
            length: None,
            cable_type: None,
            status: None,
            custom_fields: None,
            relationships: None,
            tags: None,
        }
    }
}
