/*
 * API Documentation
 *
 * Source of truth and network automation platform
 *
 * The version of the OpenAPI document: 3.2.2 (3.2)
 *
 * Generated by: https://openapi-generator.tech
 */

/// PatchedBulkWritableIpAddressRangeRequest : Base class to use for serializers based on OrganizationalModel or PrimaryModel.  Can also be used for models derived from BaseModel, so long as they support custom fields, notes, and relationships.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PatchedBulkWritableIpAddressRangeRequest {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "start_address", skip_serializing_if = "Option::is_none")]
    pub start_address: Option<String>,
    #[serde(rename = "end_address", skip_serializing_if = "Option::is_none")]
    pub end_address: Option<String>,
    #[serde(rename = "namespace", skip_serializing_if = "Option::is_none")]
    pub namespace: Option<Box<crate::models::BulkWritableIpAddressRangeRequestNamespace>>,
    /// Name of the IP Address Range
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Forces this range to count as fully utilized in prefix utilization calculations.
    #[serde(rename = "count_as_utilized", skip_serializing_if = "Option::is_none")]
    pub count_as_utilized: Option<bool>,
    /// Prevent individual IP Address objects from being created within this range.
    #[serde(rename = "is_exclusive", skip_serializing_if = "Option::is_none")]
    pub is_exclusive: Option<bool>,
    #[serde(rename = "parent", skip_serializing_if = "Option::is_none")]
    pub parent: Option<Box<crate::models::BulkWritableIpAddressRangeRequestParent>>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<Box<crate::models::BulkWritableCableRequestStatus>>,
    #[serde(
        rename = "role",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub role: Option<Option<Box<crate::models::ApprovalWorkflowUser>>>,
    #[serde(
        rename = "tenant",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub tenant: Option<Option<Box<crate::models::ApprovalWorkflowUser>>>,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<crate::models::BulkWritableCableRequestStatus>>,
    /// Custom field data for this object, keyed by each applicable Custom Field's `key`. Value types vary with the custom field's type (text, integer, boolean, date, URL, JSON, select, multi-select); undefined values are `null`. On write, the payload is merged with existing values (PATCH-style: keys omitted from the payload are left untouched), and keys that do not correspond to a defined custom field are ignored.
    #[serde(rename = "custom_fields", skip_serializing_if = "Option::is_none")]
    pub custom_fields: Option<::std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "relationships", skip_serializing_if = "Option::is_none")]
    pub relationships: Option<
        ::std::collections::HashMap<
            String,
            crate::models::ApprovalWorkflowDefinitionRequestRelationshipsValue,
        >,
    >,
}

impl PatchedBulkWritableIpAddressRangeRequest {
    /// Base class to use for serializers based on OrganizationalModel or PrimaryModel.  Can also be used for models derived from BaseModel, so long as they support custom fields, notes, and relationships.
    pub fn new(id: uuid::Uuid) -> PatchedBulkWritableIpAddressRangeRequest {
        PatchedBulkWritableIpAddressRangeRequest {
            id,
            start_address: None,
            end_address: None,
            namespace: None,
            name: None,
            description: None,
            count_as_utilized: None,
            is_exclusive: None,
            parent: None,
            status: None,
            role: None,
            tenant: None,
            tags: None,
            custom_fields: None,
            relationships: None,
        }
    }
}
