/*
 * API Documentation
 *
 * Source of truth and network automation platform
 *
 * The version of the OpenAPI document: 2.4.20 (2.4)
 *
 * Generated by: https://openapi-generator.tech
 */

/// PatchedBulkWritableModuleFamilyRequest : API serializer for ModuleFamily objects.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PatchedBulkWritableModuleFamilyRequest {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "custom_fields", skip_serializing_if = "Option::is_none")]
    pub custom_fields: Option<::std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "relationships", skip_serializing_if = "Option::is_none")]
    pub relationships: Option<
        ::std::collections::HashMap<
            String,
            crate::models::BulkWritableCableRequestRelationshipsValue,
        >,
    >,
}

impl PatchedBulkWritableModuleFamilyRequest {
    /// API serializer for ModuleFamily objects.
    pub fn new(id: uuid::Uuid) -> PatchedBulkWritableModuleFamilyRequest {
        PatchedBulkWritableModuleFamilyRequest {
            id,
            name: None,
            description: None,
            custom_fields: None,
            relationships: None,
        }
    }
}
