/*
 * API Documentation
 *
 * Source of truth and network automation platform
 *
 * The version of the OpenAPI document: 2.4.20 (2.4)
 *
 * Generated by: https://openapi-generator.tech
 */

/// RackGroupRequest : Add a `tree_depth` field to non-nested model serializers based on django-tree-queries.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RackGroupRequest {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<uuid::Uuid>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(
        rename = "parent",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub parent: Option<Option<Box<crate::models::BulkWritableCircuitRequestTenant>>>,
    #[serde(rename = "location")]
    pub location: Box<crate::models::BulkWritableCableRequestStatus>,
    #[serde(rename = "custom_fields", skip_serializing_if = "Option::is_none")]
    pub custom_fields: Option<::std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "relationships", skip_serializing_if = "Option::is_none")]
    pub relationships: Option<
        ::std::collections::HashMap<
            String,
            crate::models::BulkWritableCableRequestRelationshipsValue,
        >,
    >,
}

impl RackGroupRequest {
    /// Add a `tree_depth` field to non-nested model serializers based on django-tree-queries.
    pub fn new(
        name: String,
        location: crate::models::BulkWritableCableRequestStatus,
    ) -> RackGroupRequest {
        RackGroupRequest {
            id: None,
            name,
            description: None,
            parent: None,
            location: Box::new(location),
            custom_fields: None,
            relationships: None,
        }
    }
}
