/*
 * API Documentation
 *
 * Source of truth and network automation platform
 *
 * The version of the OpenAPI document: 2.4.20 (2.4)
 *
 * Generated by: https://openapi-generator.tech
 */

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RegulatoryDomainEnum {
    #[serde(rename = "AD")]
    Ad,
    #[serde(rename = "AE")]
    Ae,
    #[serde(rename = "AL")]
    Al,
    #[serde(rename = "AM")]
    Am,
    #[serde(rename = "AU")]
    Au,
    #[serde(rename = "AR")]
    Ar,
    #[serde(rename = "AT")]
    At,
    #[serde(rename = "AZ")]
    Az,
    #[serde(rename = "BA")]
    Ba,
    #[serde(rename = "BE")]
    Be,
    #[serde(rename = "BG")]
    Bg,
    #[serde(rename = "BH")]
    Bh,
    #[serde(rename = "BN")]
    Bn,
    #[serde(rename = "BO")]
    Bo,
    #[serde(rename = "BR")]
    Br,
    #[serde(rename = "BS")]
    Bs,
    #[serde(rename = "BY")]
    By,
    #[serde(rename = "BZ")]
    Bz,
    #[serde(rename = "CA")]
    Ca,
    #[serde(rename = "CH")]
    Ch,
    #[serde(rename = "CI")]
    Ci,
    #[serde(rename = "CL")]
    Cl,
    #[serde(rename = "CN")]
    Cn,
    #[serde(rename = "CO")]
    Co,
    #[serde(rename = "CR")]
    Cr,
    #[serde(rename = "RS")]
    Rs,
    #[serde(rename = "CY")]
    Cy,
    #[serde(rename = "CZ")]
    Cz,
    #[serde(rename = "DE")]
    De,
    #[serde(rename = "DK")]
    Dk,
    #[serde(rename = "DO")]
    Do,
    #[serde(rename = "DZ")]
    Dz,
    #[serde(rename = "EC")]
    Ec,
    #[serde(rename = "EE")]
    Ee,
    #[serde(rename = "EG")]
    Eg,
    #[serde(rename = "ES")]
    Es,
    #[serde(rename = "FO")]
    Fo,
    #[serde(rename = "FI")]
    Fi,
    #[serde(rename = "FR")]
    Fr,
    #[serde(rename = "GB")]
    Gb,
    #[serde(rename = "GE")]
    Ge,
    #[serde(rename = "GI")]
    Gi,
    #[serde(rename = "GL")]
    Gl,
    #[serde(rename = "GP")]
    Gp,
    #[serde(rename = "GR")]
    Gr,
    #[serde(rename = "GT")]
    Gt,
    #[serde(rename = "GY")]
    Gy,
    #[serde(rename = "HN")]
    Hn,
    #[serde(rename = "HK")]
    Hk,
    #[serde(rename = "HR")]
    Hr,
    #[serde(rename = "HU")]
    Hu,
    #[serde(rename = "IS")]
    Is,
    #[serde(rename = "IN")]
    In,
    #[serde(rename = "ID")]
    Id,
    #[serde(rename = "IE")]
    Ie,
    #[serde(rename = "IL")]
    Il,
    #[serde(rename = "IQ")]
    Iq,
    #[serde(rename = "IT")]
    It,
    #[serde(rename = "IR")]
    Ir,
    #[serde(rename = "JM")]
    Jm,
    #[serde(rename = "JO")]
    Jo,
    #[serde(rename = "JP")]
    Jp,
    #[serde(rename = "KP")]
    Kp,
    #[serde(rename = "KR")]
    Kr,
    #[serde(rename = "KE")]
    Ke,
    #[serde(rename = "KW")]
    Kw,
    #[serde(rename = "KZ")]
    Kz,
    #[serde(rename = "LB")]
    Lb,
    #[serde(rename = "LI")]
    Li,
    #[serde(rename = "LK")]
    Lk,
    #[serde(rename = "LT")]
    Lt,
    #[serde(rename = "LU")]
    Lu,
    #[serde(rename = "LV")]
    Lv,
    #[serde(rename = "LY")]
    Ly,
    #[serde(rename = "MA")]
    Ma,
    #[serde(rename = "MC")]
    Mc,
    #[serde(rename = "MD")]
    Md,
    #[serde(rename = "MK")]
    Mk,
    #[serde(rename = "MO")]
    Mo,
    #[serde(rename = "MQ")]
    Mq,
    #[serde(rename = "MT")]
    Mt,
    #[serde(rename = "MU")]
    Mu,
    #[serde(rename = "MX")]
    Mx,
    #[serde(rename = "MY")]
    My,
    #[serde(rename = "NA")]
    Na,
    #[serde(rename = "NG")]
    Ng,
    #[serde(rename = "NI")]
    Ni,
    #[serde(rename = "NL")]
    Nl,
    #[serde(rename = "NO")]
    No,
    #[serde(rename = "NZ")]
    Nz,
    #[serde(rename = "OM")]
    Om,
    #[serde(rename = "PA")]
    Pa,
    #[serde(rename = "PE")]
    Pe,
    #[serde(rename = "PL")]
    Pl,
    #[serde(rename = "PH")]
    Ph,
    #[serde(rename = "PK")]
    Pk,
    #[serde(rename = "PR")]
    Pr,
    #[serde(rename = "PT")]
    Pt,
    #[serde(rename = "PY")]
    Py,
    #[serde(rename = "QA")]
    Qa,
    #[serde(rename = "RO")]
    Ro,
    #[serde(rename = "RU")]
    Ru,
    #[serde(rename = "SA")]
    Sa,
    #[serde(rename = "SE")]
    Se,
    #[serde(rename = "SG")]
    Sg,
    #[serde(rename = "SI")]
    Si,
    #[serde(rename = "SK")]
    Sk,
    #[serde(rename = "SM")]
    Sm,
    #[serde(rename = "SV")]
    Sv,
    #[serde(rename = "SY")]
    Sy,
    #[serde(rename = "TH")]
    Th,
    #[serde(rename = "TN")]
    Tn,
    #[serde(rename = "TR")]
    Tr,
    #[serde(rename = "TT")]
    Tt,
    #[serde(rename = "TW")]
    Tw,
    #[serde(rename = "UA")]
    Ua,
    #[serde(rename = "US")]
    Us,
    #[serde(rename = "UY")]
    Uy,
    #[serde(rename = "UZ")]
    Uz,
    #[serde(rename = "VA")]
    Va,
    #[serde(rename = "VE")]
    Ve,
    #[serde(rename = "VI")]
    Vi,
    #[serde(rename = "VN")]
    Vn,
    #[serde(rename = "YE")]
    Ye,
    #[serde(rename = "ZA")]
    Za,
    #[serde(rename = "ZW")]
    Zw,
}

impl ToString for RegulatoryDomainEnum {
    fn to_string(&self) -> String {
        match self {
            Self::Ad => String::from("AD"),
            Self::Ae => String::from("AE"),
            Self::Al => String::from("AL"),
            Self::Am => String::from("AM"),
            Self::Au => String::from("AU"),
            Self::Ar => String::from("AR"),
            Self::At => String::from("AT"),
            Self::Az => String::from("AZ"),
            Self::Ba => String::from("BA"),
            Self::Be => String::from("BE"),
            Self::Bg => String::from("BG"),
            Self::Bh => String::from("BH"),
            Self::Bn => String::from("BN"),
            Self::Bo => String::from("BO"),
            Self::Br => String::from("BR"),
            Self::Bs => String::from("BS"),
            Self::By => String::from("BY"),
            Self::Bz => String::from("BZ"),
            Self::Ca => String::from("CA"),
            Self::Ch => String::from("CH"),
            Self::Ci => String::from("CI"),
            Self::Cl => String::from("CL"),
            Self::Cn => String::from("CN"),
            Self::Co => String::from("CO"),
            Self::Cr => String::from("CR"),
            Self::Rs => String::from("RS"),
            Self::Cy => String::from("CY"),
            Self::Cz => String::from("CZ"),
            Self::De => String::from("DE"),
            Self::Dk => String::from("DK"),
            Self::Do => String::from("DO"),
            Self::Dz => String::from("DZ"),
            Self::Ec => String::from("EC"),
            Self::Ee => String::from("EE"),
            Self::Eg => String::from("EG"),
            Self::Es => String::from("ES"),
            Self::Fo => String::from("FO"),
            Self::Fi => String::from("FI"),
            Self::Fr => String::from("FR"),
            Self::Gb => String::from("GB"),
            Self::Ge => String::from("GE"),
            Self::Gi => String::from("GI"),
            Self::Gl => String::from("GL"),
            Self::Gp => String::from("GP"),
            Self::Gr => String::from("GR"),
            Self::Gt => String::from("GT"),
            Self::Gy => String::from("GY"),
            Self::Hn => String::from("HN"),
            Self::Hk => String::from("HK"),
            Self::Hr => String::from("HR"),
            Self::Hu => String::from("HU"),
            Self::Is => String::from("IS"),
            Self::In => String::from("IN"),
            Self::Id => String::from("ID"),
            Self::Ie => String::from("IE"),
            Self::Il => String::from("IL"),
            Self::Iq => String::from("IQ"),
            Self::It => String::from("IT"),
            Self::Ir => String::from("IR"),
            Self::Jm => String::from("JM"),
            Self::Jo => String::from("JO"),
            Self::Jp => String::from("JP"),
            Self::Kp => String::from("KP"),
            Self::Kr => String::from("KR"),
            Self::Ke => String::from("KE"),
            Self::Kw => String::from("KW"),
            Self::Kz => String::from("KZ"),
            Self::Lb => String::from("LB"),
            Self::Li => String::from("LI"),
            Self::Lk => String::from("LK"),
            Self::Lt => String::from("LT"),
            Self::Lu => String::from("LU"),
            Self::Lv => String::from("LV"),
            Self::Ly => String::from("LY"),
            Self::Ma => String::from("MA"),
            Self::Mc => String::from("MC"),
            Self::Md => String::from("MD"),
            Self::Mk => String::from("MK"),
            Self::Mo => String::from("MO"),
            Self::Mq => String::from("MQ"),
            Self::Mt => String::from("MT"),
            Self::Mu => String::from("MU"),
            Self::Mx => String::from("MX"),
            Self::My => String::from("MY"),
            Self::Na => String::from("NA"),
            Self::Ng => String::from("NG"),
            Self::Ni => String::from("NI"),
            Self::Nl => String::from("NL"),
            Self::No => String::from("NO"),
            Self::Nz => String::from("NZ"),
            Self::Om => String::from("OM"),
            Self::Pa => String::from("PA"),
            Self::Pe => String::from("PE"),
            Self::Pl => String::from("PL"),
            Self::Ph => String::from("PH"),
            Self::Pk => String::from("PK"),
            Self::Pr => String::from("PR"),
            Self::Pt => String::from("PT"),
            Self::Py => String::from("PY"),
            Self::Qa => String::from("QA"),
            Self::Ro => String::from("RO"),
            Self::Ru => String::from("RU"),
            Self::Sa => String::from("SA"),
            Self::Se => String::from("SE"),
            Self::Sg => String::from("SG"),
            Self::Si => String::from("SI"),
            Self::Sk => String::from("SK"),
            Self::Sm => String::from("SM"),
            Self::Sv => String::from("SV"),
            Self::Sy => String::from("SY"),
            Self::Th => String::from("TH"),
            Self::Tn => String::from("TN"),
            Self::Tr => String::from("TR"),
            Self::Tt => String::from("TT"),
            Self::Tw => String::from("TW"),
            Self::Ua => String::from("UA"),
            Self::Us => String::from("US"),
            Self::Uy => String::from("UY"),
            Self::Uz => String::from("UZ"),
            Self::Va => String::from("VA"),
            Self::Ve => String::from("VE"),
            Self::Vi => String::from("VI"),
            Self::Vn => String::from("VN"),
            Self::Ye => String::from("YE"),
            Self::Za => String::from("ZA"),
            Self::Zw => String::from("ZW"),
        }
    }
}

impl Default for RegulatoryDomainEnum {
    fn default() -> RegulatoryDomainEnum {
        Self::Ad
    }
}
