/*
 * API Documentation
 *
 * Source of truth and network automation platform
 *
 * The version of the OpenAPI document: 3.1.3 (3.1)
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ScheduledJobState {
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<Value>,
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<Label>,
}

impl ScheduledJobState {
    pub fn new() -> ScheduledJobState {
        ScheduledJobState {
            value: None,
            label: None,
        }
    }
}

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Value {
    #[serde(rename = "active")]
    Active,
    #[serde(rename = "pending")]
    Pending,
    #[serde(rename = "denied")]
    Denied,
    #[serde(rename = "canceled")]
    Canceled,
    #[serde(rename = "completed")]
    Completed,
    #[serde(rename = "errored")]
    Errored,
}

impl Default for Value {
    fn default() -> Value {
        Self::Active
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Label {
    #[serde(rename = "Active")]
    Active,
    #[serde(rename = "Pending Approval")]
    PendingApproval,
    #[serde(rename = "Approval Denied")]
    ApprovalDenied,
    #[serde(rename = "Approval Canceled")]
    ApprovalCanceled,
    #[serde(rename = "Completed")]
    Completed,
    #[serde(rename = "Errored")]
    Errored,
}

impl Default for Label {
    fn default() -> Label {
        Self::Active
    }
}
