/*
 * API Documentation
 *
 * Source of truth and network automation platform
 *
 * The version of the OpenAPI document: 3.2.2 (3.2)
 *
 * Generated by: https://openapi-generator.tech
 */

/// SecretsGroupRequest : Serializer for `SecretsGroup` objects.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SecretsGroupRequest {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<uuid::Uuid>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Custom field data for this object, keyed by each applicable Custom Field's `key`. Value types vary with the custom field's type (text, integer, boolean, date, URL, JSON, select, multi-select); undefined values are `null`. On write, the payload is merged with existing values (PATCH-style: keys omitted from the payload are left untouched), and keys that do not correspond to a defined custom field are ignored.
    #[serde(rename = "custom_fields", skip_serializing_if = "Option::is_none")]
    pub custom_fields: Option<::std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "relationships", skip_serializing_if = "Option::is_none")]
    pub relationships: Option<
        ::std::collections::HashMap<
            String,
            crate::models::ApprovalWorkflowDefinitionRequestRelationshipsValue,
        >,
    >,
}

impl SecretsGroupRequest {
    /// Serializer for `SecretsGroup` objects.
    pub fn new(name: String) -> SecretsGroupRequest {
        SecretsGroupRequest {
            id: None,
            name,
            description: None,
            custom_fields: None,
            relationships: None,
        }
    }
}
