/*
 * API Documentation
 *
 * Source of truth and network automation platform
 *
 * The version of the OpenAPI document: 3.1.3 (3.1)
 *
 * Generated by: https://openapi-generator.tech
 */

/// SecretsGroupAssociationRequest : Serializer for `SecretsGroupAssociation` objects.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SecretsGroupAssociationRequest {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<uuid::Uuid>,
    #[serde(rename = "access_type")]
    pub access_type: crate::models::AccessTypeEnum,
    #[serde(rename = "secret_type")]
    pub secret_type: crate::models::SecretTypeEnum,
    #[serde(rename = "secrets_group")]
    pub secrets_group: Box<crate::models::ApprovalWorkflowStageResponseApprovalWorkflowStage>,
    #[serde(rename = "secret")]
    pub secret: Box<crate::models::ApprovalWorkflowStageResponseApprovalWorkflowStage>,
}

impl SecretsGroupAssociationRequest {
    /// Serializer for `SecretsGroupAssociation` objects.
    pub fn new(
        access_type: crate::models::AccessTypeEnum,
        secret_type: crate::models::SecretTypeEnum,
        secrets_group: crate::models::ApprovalWorkflowStageResponseApprovalWorkflowStage,
        secret: crate::models::ApprovalWorkflowStageResponseApprovalWorkflowStage,
    ) -> SecretsGroupAssociationRequest {
        SecretsGroupAssociationRequest {
            id: None,
            access_type,
            secret_type,
            secrets_group: Box::new(secrets_group),
            secret: Box::new(secret),
        }
    }
}
