/*
 * API Documentation
 *
 * Source of truth and network automation platform
 *
 * The version of the OpenAPI document: 3.1.2 (3.1)
 *
 * Generated by: https://openapi-generator.tech
 */

/// SecretsGroupAssociation : Serializer for `SecretsGroupAssociation` objects.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SecretsGroupAssociation {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<uuid::Uuid>,
    #[serde(rename = "object_type", skip_serializing_if = "Option::is_none")]
    pub object_type: Option<String>,
    /// Human friendly display value
    #[serde(rename = "display", skip_serializing_if = "Option::is_none")]
    pub display: Option<String>,
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    #[serde(rename = "natural_slug", skip_serializing_if = "Option::is_none")]
    pub natural_slug: Option<String>,
    #[serde(rename = "access_type")]
    pub access_type: crate::models::AccessTypeEnum,
    #[serde(rename = "secret_type")]
    pub secret_type: crate::models::SecretTypeEnum,
    #[serde(rename = "secrets_group")]
    pub secrets_group: Box<crate::models::ApprovalWorkflowStageResponseApprovalWorkflowStage>,
    #[serde(rename = "secret")]
    pub secret: Box<crate::models::ApprovalWorkflowStageResponseApprovalWorkflowStage>,
}

impl SecretsGroupAssociation {
    /// Serializer for `SecretsGroupAssociation` objects.
    pub fn new(
        access_type: crate::models::AccessTypeEnum,
        secret_type: crate::models::SecretTypeEnum,
        secrets_group: crate::models::ApprovalWorkflowStageResponseApprovalWorkflowStage,
        secret: crate::models::ApprovalWorkflowStageResponseApprovalWorkflowStage,
    ) -> SecretsGroupAssociation {
        SecretsGroupAssociation {
            id: None,
            object_type: None,
            display: None,
            url: None,
            natural_slug: None,
            access_type,
            secret_type,
            secrets_group: Box::new(secrets_group),
            secret: Box::new(secret),
        }
    }
}
