/*
 * API Documentation
 *
 * Source of truth and network automation platform
 *
 * The version of the OpenAPI document: 2.4.20 (2.4)
 *
 * Generated by: https://openapi-generator.tech
 */

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum StandardEnum {
    #[serde(rename = "802.11a")]
    Variant11a,
    #[serde(rename = "802.11b")]
    Variant11b,
    #[serde(rename = "802.11g")]
    Variant11g,
    #[serde(rename = "802.11n")]
    Variant11n,
    #[serde(rename = "802.11ac")]
    Variant11ac,
    #[serde(rename = "802.11ax")]
    Variant11ax,
    #[serde(rename = "802.11be")]
    Variant11be,
}

impl ToString for StandardEnum {
    fn to_string(&self) -> String {
        match self {
            Self::Variant11a => String::from("802.11a"),
            Self::Variant11b => String::from("802.11b"),
            Self::Variant11g => String::from("802.11g"),
            Self::Variant11n => String::from("802.11n"),
            Self::Variant11ac => String::from("802.11ac"),
            Self::Variant11ax => String::from("802.11ax"),
            Self::Variant11be => String::from("802.11be"),
        }
    }
}

impl Default for StandardEnum {
    fn default() -> StandardEnum {
        Self::Variant11a
    }
}
