/*
 * API Documentation
 *
 * Source of truth and network automation platform
 *
 * The version of the OpenAPI document: 2.4.27 (2.4)
 *
 * Generated by: https://openapi-generator.tech
 */

/// Stats : Serializer for rendering linkable statistics, e.g. related object counts for a Location.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Stats {
    #[serde(rename = "title")]
    pub title: String,
    #[serde(rename = "count")]
    pub count: i32,
    #[serde(rename = "ui_url")]
    pub ui_url: String,
    #[serde(rename = "api_url")]
    pub api_url: String,
}

impl Stats {
    /// Serializer for rendering linkable statistics, e.g. related object counts for a Location.
    pub fn new(title: String, count: i32, ui_url: String, api_url: String) -> Stats {
        Stats {
            title,
            count,
            ui_url,
            api_url,
        }
    }
}
