/*
 * API Documentation
 *
 * Source of truth and network automation platform
 *
 * The version of the OpenAPI document: 2.4.20 (2.4)
 *
 * Generated by: https://openapi-generator.tech
 */

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SupplyEnum {
    #[serde(rename = "ac")]
    Ac,
    #[serde(rename = "dc")]
    Dc,
}

impl ToString for SupplyEnum {
    fn to_string(&self) -> String {
        match self {
            Self::Ac => String::from("ac"),
            Self::Dc => String::from("dc"),
        }
    }
}

impl Default for SupplyEnum {
    fn default() -> SupplyEnum {
        Self::Ac
    }
}
