/*
 * API Documentation
 *
 * Source of truth and network automation platform
 *
 * The version of the OpenAPI document: 2.4.20 (2.4)
 *
 * Generated by: https://openapi-generator.tech
 */

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TermSideEnum {
    #[serde(rename = "A")]
    A,
    #[serde(rename = "Z")]
    Z,
}

impl ToString for TermSideEnum {
    fn to_string(&self) -> String {
        match self {
            Self::A => String::from("A"),
            Self::Z => String::from("Z"),
        }
    }
}

impl Default for TermSideEnum {
    fn default() -> TermSideEnum {
        Self::A
    }
}
