/*
 * API Documentation
 *
 * Source of truth and network automation platform
 *
 * The version of the OpenAPI document: 3.1.2 (3.1)
 *
 * Generated by: https://openapi-generator.tech
 */

/// UserSavedViewAssociationRequest : Extends the built-in ModelSerializer to enforce calling full_clean() on a copy of the associated instance during validation. (DRF does not do this by default; see <https://github.com/encode/django-rest-framework/issues/3144>)

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UserSavedViewAssociationRequest {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<uuid::Uuid>,
    #[serde(rename = "view_name")]
    pub view_name: String,
    #[serde(rename = "saved_view")]
    pub saved_view: Box<crate::models::ApprovalWorkflowStageResponseApprovalWorkflowStage>,
    #[serde(rename = "user")]
    pub user: Box<crate::models::ApprovalWorkflowStageResponseApprovalWorkflowStage>,
}

impl UserSavedViewAssociationRequest {
    /// Extends the built-in ModelSerializer to enforce calling full_clean() on a copy of the associated instance during validation. (DRF does not do this by default; see <https://github.com/encode/django-rest-framework/issues/3144>)
    pub fn new(
        view_name: String,
        saved_view: crate::models::ApprovalWorkflowStageResponseApprovalWorkflowStage,
        user: crate::models::ApprovalWorkflowStageResponseApprovalWorkflowStage,
    ) -> UserSavedViewAssociationRequest {
        UserSavedViewAssociationRequest {
            id: None,
            view_name,
            saved_view: Box::new(saved_view),
            user: Box::new(user),
        }
    }
}
