/*
 * API Documentation
 *
 * Source of truth and network automation platform
 *
 * The version of the OpenAPI document: 3.1.6 (3.1)
 *
 * Generated by: https://openapi-generator.tech
 */

/// VirtualServerCertificateProfileAssignmentRequest : VirtualServerCertificateProfileAssignment Serializer.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct VirtualServerCertificateProfileAssignmentRequest {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<uuid::Uuid>,
    #[serde(rename = "virtual_server")]
    pub virtual_server: Box<crate::models::ApprovalWorkflowStageResponseApprovalWorkflowStage>,
    #[serde(rename = "certificate_profile")]
    pub certificate_profile: Box<crate::models::ApprovalWorkflowStageResponseApprovalWorkflowStage>,
}

impl VirtualServerCertificateProfileAssignmentRequest {
    /// VirtualServerCertificateProfileAssignment Serializer.
    pub fn new(
        virtual_server: crate::models::ApprovalWorkflowStageResponseApprovalWorkflowStage,
        certificate_profile: crate::models::ApprovalWorkflowStageResponseApprovalWorkflowStage,
    ) -> VirtualServerCertificateProfileAssignmentRequest {
        VirtualServerCertificateProfileAssignmentRequest {
            id: None,
            virtual_server: Box::new(virtual_server),
            certificate_profile: Box::new(certificate_profile),
        }
    }
}
