/*
 * API Documentation
 *
 * Source of truth and network automation platform
 *
 * The version of the OpenAPI document: 3.1.2 (3.1)
 *
 * Generated by: https://openapi-generator.tech
 */

/// VpnTerminationRequest : Serializer for VPNTermination.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct VpnTerminationRequest {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<uuid::Uuid>,
    #[serde(rename = "vpn")]
    pub vpn: Box<crate::models::ApprovalWorkflowStageResponseApprovalWorkflowStage>,
    #[serde(
        rename = "vlan",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub vlan: Option<Option<Box<crate::models::ApprovalWorkflowUser>>>,
    #[serde(
        rename = "interface",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub interface: Option<Option<Box<crate::models::ApprovalWorkflowUser>>>,
    #[serde(
        rename = "vm_interface",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub vm_interface: Option<Option<Box<crate::models::ApprovalWorkflowUser>>>,
    #[serde(rename = "custom_fields", skip_serializing_if = "Option::is_none")]
    pub custom_fields: Option<::std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "relationships", skip_serializing_if = "Option::is_none")]
    pub relationships: Option<
        ::std::collections::HashMap<
            String,
            crate::models::ApprovalWorkflowDefinitionRequestRelationshipsValue,
        >,
    >,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<crate::models::ApprovalWorkflowStageResponseApprovalWorkflowStage>>,
}

impl VpnTerminationRequest {
    /// Serializer for VPNTermination.
    pub fn new(
        vpn: crate::models::ApprovalWorkflowStageResponseApprovalWorkflowStage,
    ) -> VpnTerminationRequest {
        VpnTerminationRequest {
            id: None,
            vpn: Box::new(vpn),
            vlan: None,
            interface: None,
            vm_interface: None,
            custom_fields: None,
            relationships: None,
            tags: None,
        }
    }
}
