/*
 * API Documentation
 *
 * Source of truth and network automation platform
 *
 * The version of the OpenAPI document: 3.2.2 (3.2)
 *
 * Generated by: https://openapi-generator.tech
 */

/// VpnProfilePhase1PolicyAssignmentRequest : Serializer for `VPNProfilePhase1PolicyAssignment` objects.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct VpnProfilePhase1PolicyAssignmentRequest {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<uuid::Uuid>,
    /// Higher weights appear later in the list
    #[serde(rename = "weight", skip_serializing_if = "Option::is_none")]
    pub weight: Option<i32>,
    #[serde(rename = "vpn_profile")]
    pub vpn_profile: Box<crate::models::BulkWritableCableRequestStatus>,
    #[serde(rename = "vpn_phase1_policy")]
    pub vpn_phase1_policy: Box<crate::models::BulkWritableCableRequestStatus>,
    /// Custom field data for this object, keyed by each applicable Custom Field's `key`. Value types vary with the custom field's type (text, integer, boolean, date, URL, JSON, select, multi-select); undefined values are `null`. On write, the payload is merged with existing values (PATCH-style: keys omitted from the payload are left untouched), and keys that do not correspond to a defined custom field are ignored.
    #[serde(rename = "custom_fields", skip_serializing_if = "Option::is_none")]
    pub custom_fields: Option<::std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "relationships", skip_serializing_if = "Option::is_none")]
    pub relationships: Option<
        ::std::collections::HashMap<
            String,
            crate::models::ApprovalWorkflowDefinitionRequestRelationshipsValue,
        >,
    >,
}

impl VpnProfilePhase1PolicyAssignmentRequest {
    /// Serializer for `VPNProfilePhase1PolicyAssignment` objects.
    pub fn new(
        vpn_profile: crate::models::BulkWritableCableRequestStatus,
        vpn_phase1_policy: crate::models::BulkWritableCableRequestStatus,
    ) -> VpnProfilePhase1PolicyAssignmentRequest {
        VpnProfilePhase1PolicyAssignmentRequest {
            id: None,
            weight: None,
            vpn_profile: Box::new(vpn_profile),
            vpn_phase1_policy: Box::new(vpn_phase1_policy),
            custom_fields: None,
            relationships: None,
        }
    }
}
