/*
 * API Documentation
 *
 * Source of truth and network automation platform
 *
 * The version of the OpenAPI document: 2.4.20 (2.4)
 *
 * Generated by: https://openapi-generator.tech
 */

/// WritableCableRequest : Base class to use for serializers based on OrganizationalModel or PrimaryModel.  Can also be used for models derived from BaseModel, so long as they support custom fields, notes, and relationships.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct WritableCableRequest {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<uuid::Uuid>,
    #[serde(rename = "termination_a_type")]
    pub termination_a_type: String,
    #[serde(rename = "termination_b_type")]
    pub termination_b_type: String,
    #[serde(rename = "termination_a_id")]
    pub termination_a_id: uuid::Uuid,
    #[serde(rename = "termination_b_id")]
    pub termination_b_id: uuid::Uuid,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<Box<crate::models::PatchedWritableCableRequestType>>,
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
    /// RGB color in hexadecimal (e.g. 00ff00)
    #[serde(rename = "color", skip_serializing_if = "Option::is_none")]
    pub color: Option<String>,
    #[serde(
        rename = "length",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub length: Option<Option<i32>>,
    #[serde(rename = "length_unit", skip_serializing_if = "Option::is_none")]
    pub length_unit: Option<Box<crate::models::PatchedWritableCableRequestLengthUnit>>,
    #[serde(rename = "status")]
    pub status: Box<crate::models::BulkWritableCableRequestStatus>,
    #[serde(rename = "custom_fields", skip_serializing_if = "Option::is_none")]
    pub custom_fields: Option<::std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "relationships", skip_serializing_if = "Option::is_none")]
    pub relationships: Option<
        ::std::collections::HashMap<
            String,
            crate::models::BulkWritableCableRequestRelationshipsValue,
        >,
    >,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<crate::models::BulkWritableCableRequestStatus>>,
}

impl WritableCableRequest {
    /// Base class to use for serializers based on OrganizationalModel or PrimaryModel.  Can also be used for models derived from BaseModel, so long as they support custom fields, notes, and relationships.
    pub fn new(
        termination_a_type: String,
        termination_b_type: String,
        termination_a_id: uuid::Uuid,
        termination_b_id: uuid::Uuid,
        status: crate::models::BulkWritableCableRequestStatus,
    ) -> WritableCableRequest {
        WritableCableRequest {
            id: None,
            termination_a_type,
            termination_b_type,
            termination_a_id,
            termination_b_id,
            r#type: None,
            label: None,
            color: None,
            length: None,
            length_unit: None,
            status: Box::new(status),
            custom_fields: None,
            relationships: None,
            tags: None,
        }
    }
}
