/*
 * API Documentation
 *
 * Source of truth and network automation platform
 *
 * The version of the OpenAPI document: 2.4.20 (2.4)
 *
 * Generated by: https://openapi-generator.tech
 */

/// WritableInterfaceRedundancyGroupRequest : InterfaceRedundancyGroup Serializer.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct WritableInterfaceRedundancyGroupRequest {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<uuid::Uuid>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "protocol", skip_serializing_if = "Option::is_none")]
    pub protocol: Option<Box<crate::models::RedundancyProtocol>>,
    #[serde(rename = "protocol_group_id", skip_serializing_if = "Option::is_none")]
    pub protocol_group_id: Option<String>,
    #[serde(rename = "status")]
    pub status: Box<crate::models::BulkWritableCableRequestStatus>,
    #[serde(
        rename = "secrets_group",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub secrets_group: Option<Option<Box<crate::models::BulkWritableCircuitRequestTenant>>>,
    #[serde(
        rename = "virtual_ip",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub virtual_ip: Option<Option<Box<crate::models::BulkWritableCircuitRequestTenant>>>,
    #[serde(rename = "custom_fields", skip_serializing_if = "Option::is_none")]
    pub custom_fields: Option<::std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "relationships", skip_serializing_if = "Option::is_none")]
    pub relationships: Option<
        ::std::collections::HashMap<
            String,
            crate::models::BulkWritableCableRequestRelationshipsValue,
        >,
    >,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<crate::models::BulkWritableCableRequestStatus>>,
}

impl WritableInterfaceRedundancyGroupRequest {
    /// InterfaceRedundancyGroup Serializer.
    pub fn new(
        name: String,
        status: crate::models::BulkWritableCableRequestStatus,
    ) -> WritableInterfaceRedundancyGroupRequest {
        WritableInterfaceRedundancyGroupRequest {
            id: None,
            name,
            description: None,
            protocol: None,
            protocol_group_id: None,
            status: Box::new(status),
            secrets_group: None,
            virtual_ip: None,
            custom_fields: None,
            relationships: None,
            tags: None,
        }
    }
}
